// Better Robotics — robot firmware. Mirrors firmware/pi_robot/pi_robot.py.
// LED_PIN defaults to the red LED on ESP32-CAM-MB (GPIO 33, active-low).

#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>
#include <WiFi.h>
#include <Preferences.h>
#include <Update.h>
#include <esp_heap_caps.h>
#include "esp_camera.h"
#include "version.h"  // generated by `make compile`: #define GIT_SHA "abc12345"

// AI-Thinker ESP32-CAM pin map. Matches the OV2640/OV3660/OV5640 socket on
// the standard AI-Thinker board (the one paired with CAM-MB). If a future
// board variant shows up, switch on an ifdef rather than patching in place.
#define PWDN_GPIO_NUM     32
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM      0
#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27
#define Y9_GPIO_NUM       35
#define Y8_GPIO_NUM       34
#define Y7_GPIO_NUM       39
#define Y6_GPIO_NUM       36
#define Y5_GPIO_NUM       21
#define Y4_GPIO_NUM       19
#define Y3_GPIO_NUM       18
#define Y2_GPIO_NUM        5
#define VSYNC_GPIO_NUM    25
#define HREF_GPIO_NUM     23
#define PCLK_GPIO_NUM     22

// UUIDs — must match firmware/pi_robot/pi_robot.py exactly.
#define SERVICE_UUID          "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d91"
#define LED_CHAR_UUID         "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d92"
#define WIFI_SCAN_CHAR_UUID   "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d93"
#define WIFI_JOIN_CHAR_UUID   "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d94"
#define WIFI_STATUS_CHAR_UUID "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d95"
#define OTA_DATA_CHAR_UUID    "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d96"
#define OTA_STATUS_CHAR_UUID  "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d97"
#define FW_INFO_CHAR_UUID     "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d98"
#define MOTOR_CHAR_UUID       "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d99"
// Telemetry char — system health (uptime, free heap, last reset reason).
// Same UUID Pi uses, so the dashboard's existing telemetry handler works
// across both platforms with no per-device branching.
#define TELEMETRY_CHAR_UUID   "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4d9f"
// BLE snapshot — single-frame JPEG over BLE notify, no WiFi required. The
// MJPEG-over-WiFi cap stays primary for live viewing; this is the fallback
// for "I want one frame to verify the camera works" or "Pip needs an image
// to analyze and the robot isn't on WiFi yet". Distinct UUIDs from the
// d9a/d9b WebRTC signaling pair on Pi — different intent, different protocol.
#define SNAPSHOT_REQUEST_CHAR_UUID "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4da0"
#define SNAPSHOT_DATA_CHAR_UUID    "a5f7c4d2-1b8e-4b9a-9c3d-5e8a7b6c4da1"

// Motor watchdog: every write resets the timer; silence reverts to (0, 0).
// Safe default on disconnect — no redundant channel required.
const unsigned long MOTOR_WATCHDOG_MS = 500;

// Control-loop invariants — see .claude/CLAUDE.md. LLM-issued motion is a
// 4-byte motor-char payload [l, r, dur_hi, dur_lo] that the firmware auto-
// stops after dur_ms. Magnitude + duration are clamped to these caps
// regardless of what the dashboard sent; firmware is the safety floor,
// not Pip / Claude.
const int8_t  LLM_MAX_SPEED        = 40;
const uint16_t LLM_MAX_DURATION_MS = 2000;

// Shared BLE OTA protocol (matches firmware/pi_robot/pi_robot.py):
//   ota-data   (write)    — binary frames with 1-byte opcode:
//       0x00                 abort — drop any in-flight Update state
//       0x01 [size:u32 BE]   begin-stream — reset, expect `size` bytes over BLE
//       0x02 [payload]       chunk — append to flash
//       0x03                 commit — finalize OTA + restart
//       0x04 [json]          fetch-url — accepted wire-wise, replies "failed"
//                            in this build. HTTPClient + NetworkClientSecure
//                            + mbedTLS were cut to fit IRAM once camera libs
//                            landed; dashboard's grace-window logic then falls
//                            back to BLE-stream OTA (slower, same result).
//   ota-status (read+notify) — UTF-8 JSON: {"st":...,"n":...,"total":...,"err":...}
//   fw-info    (read)     — UTF-8 JSON: {"type":"esp32","url":"firmware/bins/esp32_robot.bin"}
// The dashboard reads fw-info to know where to fetch the update binary from.

// Shared BLE WiFi spec (matches firmware/pi_robot/pi_robot.py):
//   wifi-scan   — read + notify. UTF-8 JSON: [{"s":ssid,"r":0..100,"p":0|1}].
//                 Reading triggers a rescan; notify fires when done. Strongest first.
//   wifi-join   — write. UTF-8 JSON: {"s":ssid,"p":password}. Empty p for open nets.
//   wifi-status — read + notify. UTF-8 JSON: {"st":state,"ssid":name,"err":msg}.
//                 States: idle, joining, joined, failed. (Scan activity is
//                 tracked client-side via wifi-scan notifications; it doesn't
//                 change connection state.)

const int LED_PIN = 33;
const size_t SCAN_MAX = 10;

BLECharacteristic* ledChar        = nullptr;
BLECharacteristic* wifiScanChar   = nullptr;
BLECharacteristic* wifiJoinChar   = nullptr;
BLECharacteristic* wifiStatusChar = nullptr;
BLECharacteristic* telemetryChar  = nullptr;
static unsigned long lastTelemetryAt = 0;
static const unsigned long TELEMETRY_INTERVAL_MS = 10000;

BLECharacteristic* snapshotRequestChar = nullptr;
BLECharacteristic* snapshotDataChar    = nullptr;
static TaskHandle_t snapshotTaskHandle = nullptr;
// Snapshot chunk size — must fit under MTU-3. Matches public/ble.js CHUNK_BYTES
// (180), which is conservative for desktop Chrome's negotiated MTU (~185).
static const size_t SNAPSHOT_CHUNK_BYTES = 180;
BLECharacteristic* otaDataChar    = nullptr;
BLECharacteristic* otaStatusChar  = nullptr;
BLECharacteristic* fwInfoChar     = nullptr;
BLECharacteristic* motorChar      = nullptr;

int8_t motorLeft = 0;
int8_t motorRight = 0;
unsigned long motorLastWriteAt = 0;
// Active pulse tracking — LLM 4-byte writes set motorPulseEndAt; loop()
// stops motors when millis() passes it. motorPulseId is bumped by every
// motor write so a joystick or newer pulse invalidates the earlier one's
// end-time check (newer write always wins).
uint32_t motorPulseId = 0;
uint32_t motorActivePulseId = 0;
unsigned long motorPulseEndAt = 0;

bool otaInProgress = false;
size_t otaExpected = 0;
size_t otaReceived = 0;
// Restart is deferred out of the BLE write callback so the ATT response
// for the commit opcode (0x03) can be sent before we reboot. Restarting
// inline makes the client see "GATT operation failed" even though the
// flash commit succeeded.
volatile bool otaRestartPending = false;

Preferences prefs;

bool ledOn = false;

static bool cameraReady = false;
static int  cameraInitError = 0;  // 0 if no init attempted or success
static TaskHandle_t streamTaskHandle = nullptr;
// fw-info notify asserts (getService() != nullptr) if called before
// service->start() — the first publish in setup() happens pre-start, so gate
// notifies until the service is live.
static bool bleServiceStarted = false;

// WiFi state machine — non-blocking, polled from loop().
enum WifiPhase { PHASE_IDLE, PHASE_SCANNING, PHASE_JOINING };
WifiPhase wifiPhase = PHASE_IDLE;
String pendingSsid;
String pendingPass;
unsigned long joinStartedAt = 0;
const unsigned long JOIN_TIMEOUT_MS = 20000;

static String jsonEscape(const String& s) {
  String out; out.reserve(s.length() + 2);
  for (size_t i = 0; i < s.length(); i++) {
    char c = s[i];
    if (c == '"' || c == '\\') { out += '\\'; out += c; }
    else if (c == '\n')        { out += "\\n"; }
    else if (c == '\r')        { out += "\\r"; }
    else if ((uint8_t)c < 0x20){ /* drop control chars */ }
    else                       { out += c; }
  }
  return out;
}

static int rssiToStrength(int rssi) {
  // Map -100..-50 dBm → 0..100.
  int s = (rssi + 100) * 2;
  if (s < 0) s = 0;
  if (s > 100) s = 100;
  return s;
}

static void publishStatus(const char* st, const String& ssid = "", const String& err = "", const String& ip = "") {
  String payload = "{\"st\":\""; payload += st; payload += "\"";
  if (ssid.length()) { payload += ",\"ssid\":\""; payload += jsonEscape(ssid); payload += "\""; }
  if (err.length())  { payload += ",\"err\":\"";  payload += jsonEscape(err);  payload += "\""; }
  if (ip.length())   { payload += ",\"ip\":\"";   payload += ip;               payload += "\""; }
  payload += "}";
  if (wifiStatusChar) {
    wifiStatusChar->setValue((uint8_t*)payload.c_str(), payload.length());
    wifiStatusChar->notify();
  }
  Serial.printf("wifi-status → %s\n", payload.c_str());
}

static void publishScan() {
  int n = WiFi.scanComplete();
  if (n < 0) n = 0;

  int idx[32];
  int count = min(n, 32);
  for (int i = 0; i < count; i++) idx[i] = i;
  for (int i = 0; i < count - 1; i++) {
    for (int j = i + 1; j < count; j++) {
      if (WiFi.RSSI(idx[j]) > WiFi.RSSI(idx[i])) { int t = idx[i]; idx[i] = idx[j]; idx[j] = t; }
    }
  }

  String payload = "[";
  size_t emitted = 0;
  String seen;
  for (int k = 0; k < count && emitted < SCAN_MAX; k++) {
    String ssid = WiFi.SSID(idx[k]);
    if (ssid.length() == 0) continue;
    String key = "\x01" + ssid + "\x01";
    if (seen.indexOf(key) >= 0) continue;
    seen += key;
    int strength = rssiToStrength(WiFi.RSSI(idx[k]));
    int secured = (WiFi.encryptionType(idx[k]) == WIFI_AUTH_OPEN) ? 0 : 1;
    if (ssid.length() > 32) ssid = ssid.substring(0, 32);
    if (emitted) payload += ",";
    payload += "{\"s\":\""; payload += jsonEscape(ssid); payload += "\"";
    payload += ",\"r\":"; payload += strength;
    payload += ",\"p\":"; payload += secured;
    payload += "}";
    emitted++;
  }
  payload += "]";
  if (wifiScanChar) {
    wifiScanChar->setValue((uint8_t*)payload.c_str(), payload.length());
    wifiScanChar->notify();
  }
  WiFi.scanDelete();
}

static unsigned long scanStartedAt = 0;
static void startScan() {
  if (wifiPhase != PHASE_IDLE) {
    Serial.printf("scan ignored — wifiPhase=%d (busy)\n", (int)wifiPhase);
    return;
  }
  // Make sure STA mode is live. Something (camera init, join-then-failed,
  // etc.) may have toggled it since boot; scan on the wrong mode returns 0.
  if (WiFi.getMode() != WIFI_STA) {
    WiFi.mode(WIFI_STA);
    delay(20);
  }
  WiFi.scanDelete();
  // Passive scan (listen for beacons, don't emit probe requests) with
  // 500ms per channel. On classic ESP32 with BLE active, the two radios
  // time-share 2.4 GHz so aggressively that active scans drop most probe
  // responses — zero APs seen. Passive + longer dwell lets WiFi catch
  // enough beacon frames to enumerate the neighborhood. Slower (~7-12s
  // vs 3-5s active) but actually works.
  //   scanNetworks(async, show_hidden, passive, max_ms_per_chan, channel)
  int rc = WiFi.scanNetworks(true, false, true, 500);
  wifiPhase = PHASE_SCANNING;
  scanStartedAt = millis();
  Serial.printf("wifi scan started (passive, rc=%d, mode=%d, sleep=%d, free heap=%u)\n",
                rc, (int)WiFi.getMode(), (int)WiFi.getSleep(), ESP.getFreeHeap());
}

static void startJoin(const String& ssid, const String& pass) {
  pendingSsid = ssid;
  pendingPass = pass;
  wifiPhase = PHASE_JOINING;
  joinStartedAt = millis();
  // No explicit disconnect — WiFi.begin() calls esp_wifi_connect() which
  // drops any existing association internally. Calling disconnect(false,...)
  // here races with the WiFi task's internal queues and asserts; calling
  // disconnect(true,...) deinits the driver and forces wifi_init to
  // re-allocate 4 RX buffers on a fragmented heap (BLE + camera have since
  // claimed DRAM) and fails.
  WiFi.begin(ssid.c_str(), pass.c_str());
  publishStatus("joining", ssid);
}

static bool initCamera() {
  camera_config_t config = {};
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer   = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk     = XCLK_GPIO_NUM;
  config.pin_pclk     = PCLK_GPIO_NUM;
  config.pin_vsync    = VSYNC_GPIO_NUM;
  config.pin_href     = HREF_GPIO_NUM;
  config.pin_sccb_sda = SIOD_GPIO_NUM;
  config.pin_sccb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn     = PWDN_GPIO_NUM;
  config.pin_reset    = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_JPEG;
  config.frame_size   = FRAMESIZE_VGA;   // 640×480. DMA is 32 KB regardless.
  config.jpeg_quality = 12;              // lower = higher quality
  // fb_count=1 even with PSRAM. Double-buffering costs ~10 KB of DRAM in
  // driver state and buys nothing at our stream rate.
  config.fb_count     = 1;
  config.fb_location  = psramFound() ? CAMERA_FB_IN_PSRAM : CAMERA_FB_IN_DRAM;
  config.grab_mode    = CAMERA_GRAB_LATEST;
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    cameraInitError = (int)err;
    Serial.printf("camera init failed: 0x%x (psram=%d)\n", err, psramFound());
    return false;
  }
  Serial.printf("camera ok, psram=%d\n", psramFound());
  return true;
}

// MJPEG over HTTP — raw WiFiServer in a FreeRTOS task. Picked over
// esp_http_server because the latter's IRAM footprint pushed us 1952 B over
// iram0_0_seg. This variant only pulls in LwIP + JPEG dataflow (camera
// driver already resident) and holds up fine for classroom-distance streams.
// Also serves POST /ota (WiFi OTA upload) + OPTIONS /ota (PNA preflight) so
// the dashboard can push firmware over the LAN when it has IP + PNA access.
static void streamTask(void* param) {
  WiFiServer server(81);
  server.begin();
  Serial.println("HTTP task ready on :81 (/stream, /ota)");
  while (true) {
    WiFiClient client = server.accept();
    if (!client) { vTaskDelay(50 / portTICK_PERIOD_MS); continue; }
    client.setNoDelay(true);

    // Request-line + header parse. Cap total header read at 2 s to avoid
    // parking the task on a half-open connection.
    String method, path;
    long contentLength = -1;
    String origin;        // echoed back when present (some browsers care)
    bool   pnaRequested = false;
    {
      unsigned long headerStart = millis();
      String reqLine = client.readStringUntil('\n');
      int sp1 = reqLine.indexOf(' ');
      int sp2 = (sp1 >= 0) ? reqLine.indexOf(' ', sp1 + 1) : -1;
      if (sp1 > 0 && sp2 > sp1) {
        method = reqLine.substring(0, sp1);
        path   = reqLine.substring(sp1 + 1, sp2);
      }
      while (client.connected() && millis() - headerStart < 2000) {
        String line = client.readStringUntil('\n');
        // Trim trailing \r.
        if (line.length() && line[line.length() - 1] == '\r') line.remove(line.length() - 1);
        if (line.length() == 0) break;  // end of headers
        int colon = line.indexOf(':');
        if (colon <= 0) continue;
        String key = line.substring(0, colon);
        String val = line.substring(colon + 1);
        while (val.length() && (val[0] == ' ' || val[0] == '\t')) val.remove(0, 1);
        // Case-insensitive compare — browsers may send any casing.
        if (key.equalsIgnoreCase("Content-Length")) {
          contentLength = val.toInt();
        } else if (key.equalsIgnoreCase("Origin")) {
          origin = val;
        } else if (key.equalsIgnoreCase("Access-Control-Request-Private-Network")) {
          pnaRequested = val.equalsIgnoreCase("true");
        }
      }
    }

    if (method == "OPTIONS" && path == "/ota") {
      // PNA preflight — Chrome sends this before cross-origin → private-IP
      // POSTs. Max-Age=86400 caches it for a day so repeat OTAs skip it.
      client.print("HTTP/1.1 204 No Content\r\n"
                   "Access-Control-Allow-Origin: *\r\n"
                   "Access-Control-Allow-Methods: POST, OPTIONS\r\n"
                   "Access-Control-Allow-Headers: Content-Type\r\n"
                   "Access-Control-Allow-Private-Network: true\r\n"
                   "Access-Control-Max-Age: 86400\r\n"
                   "Content-Length: 0\r\n"
                   "Connection: close\r\n\r\n");
      (void)origin; (void)pnaRequested;  // reserved for stricter replies
      client.stop();
      continue;
    }

    if (method == "POST" && path == "/ota") {
      // Guard both bad (missing/negative) and oversized uploads — 4 MB cap
      // matches the app0 partition ceiling on min_spiffs.
      if (contentLength <= 0 || contentLength > 4 * 1024 * 1024) {
        client.print("HTTP/1.1 400 Bad Request\r\n"
                     "Access-Control-Allow-Origin: *\r\n"
                     "Content-Length: 0\r\n"
                     "Connection: close\r\n\r\n");
        client.stop();
        continue;
      }
      if (!Update.begin((size_t)contentLength)) {
        client.print("HTTP/1.1 500 Internal Server Error\r\n"
                     "Access-Control-Allow-Origin: *\r\n"
                     "Content-Length: 0\r\n"
                     "Connection: close\r\n\r\n");
        client.stop();
        continue;
      }
      uint8_t buf[2048];
      size_t received = 0;
      unsigned long lastData = millis();
      bool failed = false;
      while (received < (size_t)contentLength) {
        int avail = client.available();
        if (avail <= 0) {
          if (!client.connected()) { failed = true; break; }
          // 10 s stall timeout — abort instead of hanging the task.
          if (millis() - lastData > 10000) { failed = true; break; }
          vTaskDelay(5 / portTICK_PERIOD_MS);
          continue;
        }
        size_t want = sizeof(buf);
        size_t remaining = (size_t)contentLength - received;
        if (want > remaining) want = remaining;
        int got = client.read(buf, want);
        if (got <= 0) {
          if (millis() - lastData > 10000) { failed = true; break; }
          continue;
        }
        if (Update.write(buf, got) != (size_t)got) { failed = true; break; }
        received += got;
        lastData = millis();
      }
      if (failed) {
        Update.abort();
        client.print("HTTP/1.1 500 Internal Server Error\r\n"
                     "Access-Control-Allow-Origin: *\r\n"
                     "Content-Length: 0\r\n"
                     "Connection: close\r\n\r\n");
        client.stop();
        continue;
      }
      if (!Update.end(true)) {
        client.print("HTTP/1.1 500 Internal Server Error\r\n"
                     "Access-Control-Allow-Origin: *\r\n"
                     "Content-Length: 0\r\n"
                     "Connection: close\r\n\r\n");
        client.stop();
        continue;
      }
      client.print("HTTP/1.1 200 OK\r\n"
                   "Access-Control-Allow-Origin: *\r\n"
                   "Content-Type: text/plain\r\n"
                   "Content-Length: 2\r\n"
                   "Connection: close\r\n\r\n"
                   "OK");
      client.stop();
      // Defer restart to loop() — gives TCP FIN time to flush, matches how
      // the BLE commit path already reboots.
      otaRestartPending = true;
      continue;
    }

    if (method == "GET" && path == "/stream") {
      // CORS open so the dashboard on GitHub Pages can load the stream as <img>.
      client.print("HTTP/1.1 200 OK\r\n"
                   "Content-Type: multipart/x-mixed-replace;boundary=frame\r\n"
                   "Access-Control-Allow-Origin: *\r\n"
                   "Connection: close\r\n\r\n");
      while (client.connected()) {
        camera_fb_t *fb = esp_camera_fb_get();
        if (!fb) break;
        client.printf("\r\n--frame\r\nContent-Type: image/jpeg\r\nContent-Length: %u\r\n\r\n", fb->len);
        size_t written = client.write(fb->buf, fb->len);
        esp_camera_fb_return(fb);
        if (written != fb->len) break;  // client disconnected mid-frame
        vTaskDelay(1 / portTICK_PERIOD_MS);  // yield the core briefly
      }
      client.stop();
      continue;
    }

    client.print("HTTP/1.1 404 Not Found\r\n"
                 "Access-Control-Allow-Origin: *\r\n"
                 "Content-Length: 0\r\n"
                 "Connection: close\r\n\r\n");
    client.stop();
  }
}

static void startCameraServer() {
  if (streamTaskHandle) return;
  // Pin to core 1 — core 0 runs WiFi + BLE stacks; keep them uncontested.
  xTaskCreatePinnedToCore(streamTask, "mjpeg", 4096, nullptr, 1, &streamTaskHandle, 1);
}

static void publishFwInfo() {
  if (!fwInfoChar) return;
  // Always advertise the non-camera caps so the dashboard renders LED /
  // motors / wifi UI even when the camera failed to init. Each cap maps to
  // an existing BLE characteristic via the dashboard's UUIDS_BY_CAP table.
  String info = "{\"type\":\"esp32\",\"url\":\"firmware/bins/esp32_robot.bin\"";
  // `version` field matches the Pi's fw-info shape so the dashboard's menu
  // Git SHA stamped into firmware/esp32_robot/version.h by `make compile`;
  // matches the Pi's version.py convention so fw-info.version is symmetric
  // across platforms. "dev" when building outside git (rare — CI always has git).
  info += ",\"version\":\"" GIT_SHA "\"";
  info += ",\"caps\":[";
  info += "{\"name\":\"led\",\"type\":\"toggle\"}";
  info += ",{\"name\":\"wifi\",\"type\":\"wifi-scan\"}";
  info += ",{\"name\":\"motors\",\"type\":\"signed-pair\",\"range\":[-100,100]}";
  if (cameraReady) {
    info += ",{\"name\":\"camera\",\"type\":\"mjpeg-stream\",\"port\":81,\"path\":\"/stream\"}";
    // Snapshot is BLE-only and works without WiFi — distinct cap so the
    // dashboard can render it independently of the live-stream card.
    info += ",{\"name\":\"snapshot\",\"type\":\"ble-snapshot\"}";
  }
  info += "]";
  if (!cameraReady && cameraInitError) {
    info += ",\"camera_err\":";
    info += String(cameraInitError);
  }
  info += "}";
  fwInfoChar->setValue(info.c_str());
  // Notify only once the service is live — pre-start notify() asserts. After
  // service->start(), this pushes schema changes (camera cap appearing post-
  // WiFi-join) to any subscribed dashboard.
  if (bleServiceStarted) fwInfoChar->notify();
}

static void applyLed(bool on) {
  ledOn = on;
  digitalWrite(LED_PIN, on ? LOW : HIGH);  // active-low
  uint8_t v = on ? 1 : 0;
  if (ledChar) {
    ledChar->setValue(&v, 1);
    ledChar->notify();
  }
}

static void publishOta(const char* st, size_t n = 0, size_t total = 0, const char* err = nullptr) {
  String payload = "{\"st\":\""; payload += st; payload += "\"";
  payload += ",\"n\":"; payload += (unsigned)n;
  if (total) { payload += ",\"total\":"; payload += (unsigned)total; }
  if (err)   { payload += ",\"err\":\""; payload += err; payload += "\""; }
  payload += "}";
  if (otaStatusChar) {
    otaStatusChar->setValue((uint8_t*)payload.c_str(), payload.length());
    otaStatusChar->notify();
  }
  Serial.printf("ota-status → %s\n", payload.c_str());
}

// Rate-limit state for op 0x02 chunk-receive notifies. Reset on op 0x01.
static size_t        chunkLastReported = 0;
static unsigned long chunkLastProgress = 0;

class OtaDataCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch) override {
    String v = ch->getValue();
    if (v.length() == 0) return;
    uint8_t op = (uint8_t)v[0];
    if (op == 0x00) {
      if (otaInProgress) {
        Update.abort();
        otaInProgress = false;
      }
      otaReceived = 0;
      otaExpected = 0;
      publishOta("idle");
    } else if (op == 0x01) {
      if (v.length() < 5) { publishOta("failed", 0, 0, "bad begin"); return; }
      otaExpected = ((uint32_t)(uint8_t)v[1] << 24)
                  | ((uint32_t)(uint8_t)v[2] << 16)
                  | ((uint32_t)(uint8_t)v[3] << 8)
                  |  (uint32_t)(uint8_t)v[4];
      otaReceived = 0;
      if (!Update.begin(otaExpected)) {
        publishOta("failed", 0, otaExpected, "Update.begin failed");
        return;
      }
      otaInProgress = true;
      // Reset rate-limit window so a fresh OTA starts clean.
      chunkLastReported = 0;
      chunkLastProgress = 0;
      publishOta("receiving", 0, otaExpected);
    } else if (op == 0x02) {
      if (!otaInProgress) { publishOta("failed", 0, 0, "no active session"); return; }
      size_t len = v.length() - 1;
      size_t w = Update.write((uint8_t*)(v.c_str() + 1), len);
      if (w != len) {
        Update.abort();
        otaInProgress = false;
        publishOta("failed", otaReceived, otaExpected, "write short");
        return;
      }
      otaReceived += len;
      // 1.6 MB / 180 B/chunk ≈ 9000 notifies — throttle to avoid saturating
      // the BLE stack once the dashboard switches to writeWithoutResponse.
      unsigned long now = millis();
      if (otaReceived - chunkLastReported > 32768 || now - chunkLastProgress > 250) {
        chunkLastReported = otaReceived;
        chunkLastProgress = now;
        publishOta("receiving", otaReceived, otaExpected);
      }
    } else if (op == 0x03) {
      if (!otaInProgress) { publishOta("failed", 0, 0, "no active session"); return; }
      publishOta("committing", otaReceived, otaExpected);
      if (!Update.end(true)) {
        otaInProgress = false;
        publishOta("failed", otaReceived, otaExpected, "Update.end failed");
        return;
      }
      publishOta("done", otaReceived, otaExpected);
      otaRestartPending = true;  // loop() restarts after onWrite returns
    } else if (op == 0x04) {
      // URL-trigger isn't in this build — HTTPClient + NetworkClientSecure +
      // mbedTLS were the cheapest IRAM cuts once camera libs joined, and BLE-
      // stream is the correct fallback. Replying "failed" tells the dashboard
      // to fall back automatically (see ota.js grace-window logic).
      publishOta("failed", 0, 0, "url-trigger unavailable in camera build");
    }
  }
};

// Arduino BLE stops advertising when a central connects and doesn't
// auto-resume on disconnect — restart it here so behavior matches the Pi
// (BlueZ keeps advertising by default) and the operator can reconnect
// without power-cycling the device.
class ServerCallbacks : public BLEServerCallbacks {
  void onDisconnect(BLEServer* /*srv*/) override {
    BLEDevice::startAdvertising();
    Serial.println("client disconnected; advertising resumed");
  }
};

class LedCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch) override {
    String value = ch->getValue();
    if (value.length() > 0) applyLed(value[0] != 0);
  }
};

static void applyMotors(int8_t left, int8_t right) {
  motorLeft = left;
  motorRight = right;
  // Stub — wire your H-bridge / ledc PWM here. Current body just echoes
  // state over BLE so watchdog behavior is visible without hardware.
  uint8_t buf[2] = { (uint8_t)left, (uint8_t)right };
  if (motorChar) {
    motorChar->setValue(buf, 2);
    motorChar->notify();
  }
  Serial.printf("motors → (%+d, %+d)\n", left, right);
}

class MotorCallbacks : public BLECharacteristicCallbacks {
  // Two payload shapes, parity with pi_robot.py:
  //   2 bytes [l, r]                 — persistent (user joystick). Watchdog
  //                                    handles auto-stop on silence.
  //   4 bytes [l, r, dur_hi, dur_lo] — time-bounded pulse (LLM). Clamped
  //                                    to LLM_MAX_SPEED / LLM_MAX_DURATION_MS.
  //                                    loop() auto-stops at motorPulseEndAt.
  // Every write bumps motorPulseId so a newer write invalidates an earlier
  // pulse's pending stop.
  void onWrite(BLECharacteristic* ch) override {
    String v = ch->getValue();
    motorLastWriteAt = millis();
    motorPulseId++;
    if (v.length() == 2) {
      applyMotors((int8_t)v[0], (int8_t)v[1]);
    } else if (v.length() == 4) {
      int8_t l = (int8_t)v[0];
      int8_t r = (int8_t)v[1];
      if (l < -LLM_MAX_SPEED) l = -LLM_MAX_SPEED;
      if (l >  LLM_MAX_SPEED) l =  LLM_MAX_SPEED;
      if (r < -LLM_MAX_SPEED) r = -LLM_MAX_SPEED;
      if (r >  LLM_MAX_SPEED) r =  LLM_MAX_SPEED;
      uint16_t dur = ((uint8_t)v[2] << 8) | (uint8_t)v[3];
      if (dur < 50)                     dur = 50;
      if (dur > LLM_MAX_DURATION_MS)    dur = LLM_MAX_DURATION_MS;
      applyMotors(l, r);
      motorActivePulseId = motorPulseId;
      motorPulseEndAt = millis() + dur;
    }
  }
};

class WifiScanCallbacks : public BLECharacteristicCallbacks {
  void onRead(BLECharacteristic* /*ch*/) override { startScan(); }
};

class WifiJoinCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch) override {
    String value = ch->getValue();
    // Payload spec: {"s":"...","p":"..."}.
    int sIdx = value.indexOf("\"s\"");
    int pIdx = value.indexOf("\"p\"");
    if (sIdx < 0) { publishStatus("failed", "", "missing ssid"); return; }
    auto extract = [&](int keyIdx) -> String {
      int colon = value.indexOf(':', keyIdx);
      if (colon < 0) return "";
      int q1 = value.indexOf('"', colon);
      if (q1 < 0) return "";
      int q2 = value.indexOf('"', q1 + 1);
      while (q2 > 0 && value[q2 - 1] == '\\') q2 = value.indexOf('"', q2 + 1);
      if (q2 < 0) return "";
      return value.substring(q1 + 1, q2);
    };
    String ssid = extract(sIdx);
    String pass = (pIdx >= 0) ? extract(pIdx) : "";
    if (ssid.length() == 0) { publishStatus("failed", "", "missing ssid"); return; }
    startJoin(ssid, pass);
  }
};

// Snapshot pipeline — runs in its own FreeRTOS task so the BLE write
// callback returns immediately. Captures a frame, sends as a chunked stream
// (begin/chunk/commit; same envelope OTA uses, just outbound). One snapshot
// at a time — overlapping requests during a transfer drop the new one.
static void snapshotTask(void* param) {
  if (!cameraReady) {
    if (snapshotDataChar) {
      uint8_t err[1 + 16];
      err[0] = 0xff;
      const char* msg = "no-camera";
      size_t n = strlen(msg);
      memcpy(err + 1, msg, n);
      snapshotDataChar->setValue(err, 1 + n);
      snapshotDataChar->notify();
    }
    snapshotTaskHandle = nullptr;
    vTaskDelete(nullptr);
    return;
  }
  camera_fb_t* fb = esp_camera_fb_get();
  if (!fb) {
    if (snapshotDataChar) {
      uint8_t err[1 + 16];
      err[0] = 0xff;
      const char* msg = "fb-get-failed";
      size_t n = strlen(msg);
      memcpy(err + 1, msg, n);
      snapshotDataChar->setValue(err, 1 + n);
      snapshotDataChar->notify();
    }
    snapshotTaskHandle = nullptr;
    vTaskDelete(nullptr);
    return;
  }

  // Begin: opcode 0x01 + total size (u32 BE). Dashboard pre-allocates a
  // buffer so it can show progress (n received / total) instead of a spinner.
  uint8_t begin[5];
  begin[0] = 0x01;
  begin[1] = (fb->len >> 24) & 0xff;
  begin[2] = (fb->len >> 16) & 0xff;
  begin[3] = (fb->len >>  8) & 0xff;
  begin[4] = (fb->len      ) & 0xff;
  snapshotDataChar->setValue(begin, 5);
  snapshotDataChar->notify();

  // Chunks: opcode 0x02 + payload. Loop with small yields between to let the
  // BLE stack drain its tx queue — sending too fast on classic ESP32 BLE
  // overflows the controller and notifies silently drop.
  size_t sent = 0;
  uint8_t chunk[1 + SNAPSHOT_CHUNK_BYTES];
  chunk[0] = 0x02;
  while (sent < fb->len) {
    size_t take = fb->len - sent;
    if (take > SNAPSHOT_CHUNK_BYTES) take = SNAPSHOT_CHUNK_BYTES;
    memcpy(chunk + 1, fb->buf + sent, take);
    snapshotDataChar->setValue(chunk, 1 + take);
    snapshotDataChar->notify();
    sent += take;
    // 25 ms covers Mac/Chrome's typical 30 ms connection interval. Earlier
    // 6 ms was too aggressive — Bluedroid's notify queue (~7 entries) would
    // overflow and silently drop late chunks, leaving the dashboard stuck
    // mid-transfer. Slower but reliable: ~9 KB JPEG ≈ 50 chunks ≈ 1.3 s.
    vTaskDelay(pdMS_TO_TICKS(25));
  }

  // Commit: opcode 0x03, no payload. Dashboard validates received == total.
  uint8_t commit[1] = { 0x03 };
  snapshotDataChar->setValue(commit, 1);
  snapshotDataChar->notify();

  esp_camera_fb_return(fb);
  Serial.printf("snapshot: sent %u bytes\n", (unsigned)sent);
  snapshotTaskHandle = nullptr;
  vTaskDelete(nullptr);
}

class SnapshotRequestCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* c) override {
    String v = c->getValue();
    // Single byte 0x01 = capture. Any other opcode reserved for future use.
    if (v.length() < 1 || (uint8_t)v[0] != 0x01) return;
    if (snapshotTaskHandle != nullptr) {
      Serial.printf("snapshot: ignored — transfer in progress\n");
      return;
    }
    // 8 KB stack — chunk loop is shallow; bumped from 4 KB out of paranoia
    // on camera-frame paths.
    xTaskCreatePinnedToCore(snapshotTask, "snapshot", 8192, nullptr, 1, &snapshotTaskHandle, 1);
  }
};

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, HIGH);  // off

  // Stable per-chip suffix — low 16 bits of the WiFi MAC.
  uint64_t chipid = ESP.getEfuseMac();
  char name[32];
  snprintf(name, sizeof(name), "BetterRobot-%04X", (uint16_t)(chipid & 0xFFFF));

  // Allocation order is the whole trick on classic ESP32-CAM where
  // BLE + WiFi + esp32-camera compete for ~250 KB of DRAM:
  //   1) Camera first — claims its 32 KB contiguous DMA buffer while the
  //      heap is still unfragmented. JPEG DMA must live in internal DRAM
  //      (PSRAM isn't DMA-coherent on classic ESP32) and the driver allocates
  //      this lazily in esp_camera_init().
  //   2) BLE next — bluedroid's ~50 KB heap + semaphores for each char fit
  //      comfortably in the remaining ~210 KB. Previously we had camera
  //      compete AFTER BLE and BLE char creation would crash in
  //      FreeRTOS::Semaphore() with `xQueueGenericSend NULL pxQueue` (a
  //      failed xSemaphoreCreateBinary returning NULL).
  //   3) WiFi last — driver up on whatever's left; if it's marginal, the
  //      user at least still has a working BLE peripheral to diagnose with.
  cameraReady = initCamera();

  BLEDevice::init(name);
  BLEServer* server = BLEDevice::createServer();
  server->setCallbacks(new ServerCallbacks());
  // Default numHandles (15) silently drops characteristics past the cap.
  // Each characteristic = 2 handles (decl + val); each CCCD (2902) = 1 more.
  // 32 leaves room; exceeding the budget gives no error.
  BLEService* service = server->createService(BLEUUID(SERVICE_UUID), 32, 0);

  ledChar = service->createCharacteristic(
    LED_CHAR_UUID,
    BLECharacteristic::PROPERTY_READ
      | BLECharacteristic::PROPERTY_WRITE
      | BLECharacteristic::PROPERTY_NOTIFY
  );
  ledChar->addDescriptor(new BLE2902());
  ledChar->setCallbacks(new LedCallbacks());
  uint8_t initial = 0;
  ledChar->setValue(&initial, 1);

  wifiScanChar = service->createCharacteristic(
    WIFI_SCAN_CHAR_UUID,
    BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY
  );
  wifiScanChar->addDescriptor(new BLE2902());
  wifiScanChar->setCallbacks(new WifiScanCallbacks());
  wifiScanChar->setValue("[]");

  wifiJoinChar = service->createCharacteristic(
    WIFI_JOIN_CHAR_UUID,
    BLECharacteristic::PROPERTY_WRITE
  );
  wifiJoinChar->setCallbacks(new WifiJoinCallbacks());

  wifiStatusChar = service->createCharacteristic(
    WIFI_STATUS_CHAR_UUID,
    BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY
  );
  wifiStatusChar->addDescriptor(new BLE2902());
  wifiStatusChar->setValue("{\"st\":\"idle\"}");

  otaDataChar = service->createCharacteristic(
    OTA_DATA_CHAR_UUID,
    // WRITE | WRITE_NR — without-response lets the dashboard stream chunks
    // without per-frame ATT acks once we reintroduce the WithoutResponse
    // client-side. Advertising both keeps WithResponse as a fallback.
    BLECharacteristic::PROPERTY_WRITE | BLECharacteristic::PROPERTY_WRITE_NR
  );
  otaDataChar->setCallbacks(new OtaDataCallbacks());

  otaStatusChar = service->createCharacteristic(
    OTA_STATUS_CHAR_UUID,
    BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY
  );
  otaStatusChar->addDescriptor(new BLE2902());
  otaStatusChar->setValue("{\"st\":\"idle\"}");

  fwInfoChar = service->createCharacteristic(
    FW_INFO_CHAR_UUID,
    // NOTIFY is retained for future schema changes (e.g. cap added at
    // runtime). Today camera is init'd in setup() so the initial read already
    // has everything; dashboard subscribes defensively but won't see updates
    // in normal operation.
    BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY
  );
  fwInfoChar->addDescriptor(new BLE2902());
  publishFwInfo();

  motorChar = service->createCharacteristic(
    MOTOR_CHAR_UUID,
    BLECharacteristic::PROPERTY_READ
      | BLECharacteristic::PROPERTY_WRITE
      | BLECharacteristic::PROPERTY_NOTIFY
  );
  motorChar->addDescriptor(new BLE2902());
  motorChar->setCallbacks(new MotorCallbacks());
  uint8_t motorInit[2] = { 0, 0 };
  motorChar->setValue(motorInit, 2);

  // Telemetry: system-health observability matched to Pi's TELEMETRY_CHAR_UUID
  // shape. ESP32 has one binary so there's no "main service down, device fine"
  // state to recover from — the value here is *diagnostic*, not a separate
  // recovery plane. JSON: {uptime_ms, free_heap, free_psram, reset_reason, sha}.
  telemetryChar = service->createCharacteristic(
    TELEMETRY_CHAR_UUID,
    BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY
  );
  telemetryChar->addDescriptor(new BLE2902());
  telemetryChar->setValue("{}");

  // BLE snapshot — see snapshotTask() for the wire format. Two chars: a
  // single-byte write trigger and a notify-only outbound stream. Only
  // registered if the camera came up; saves handles otherwise (we're at 32).
  if (cameraReady) {
    snapshotRequestChar = service->createCharacteristic(
      SNAPSHOT_REQUEST_CHAR_UUID,
      BLECharacteristic::PROPERTY_WRITE
    );
    snapshotRequestChar->setCallbacks(new SnapshotRequestCallbacks());

    snapshotDataChar = service->createCharacteristic(
      SNAPSHOT_DATA_CHAR_UUID,
      BLECharacteristic::PROPERTY_NOTIFY
    );
    snapshotDataChar->addDescriptor(new BLE2902());
  }

  service->start();
  bleServiceStarted = true;

  BLEAdvertising* adv = BLEDevice::getAdvertising();
  adv->addServiceUUID(SERVICE_UUID);
  adv->setScanResponse(true);
  BLEDevice::startAdvertising();

  Serial.printf("\nAdvertising as %s\n", name);

  // WiFi last in the allocation order (see the comment at the top of setup).
  // `WiFi.mode(WIFI_STA)` runs esp_wifi_init + esp_wifi_start; after it
  // returns the driver is up and the 4 static RX buffers are allocated.
  // setSleep(false) keeps the radio awake during BLE windows (default DTIM
  // sleep drops beacons and makes scans come back empty). Max TX power
  // helps cut through the antenna shadow from an attached camera module.
  WiFi.mode(WIFI_STA);
  WiFi.setSleep(false);
  WiFi.setTxPower(WIFI_POWER_19_5dBm);
  Serial.printf("wifi up, free heap=%u, largest dma block=%u\n",
                ESP.getFreeHeap(), heap_caps_get_largest_free_block(MALLOC_CAP_DMA));

  prefs.begin("wifi", true);
  String savedSsid = prefs.getString("ssid", "");
  String savedPass = prefs.getString("pass", "");
  prefs.end();
  if (savedSsid.length()) {
    startJoin(savedSsid, savedPass);
  }
}

// Map esp_reset_reason() to a short human label. Useful when the dashboard
// surfaces a recent crash — "panic" / "watchdog" tells a different story than
// "power-on" or "deepsleep".
static const char* resetReasonLabel(esp_reset_reason_t r) {
  switch (r) {
    case ESP_RST_POWERON:  return "poweron";
    case ESP_RST_EXT:      return "ext";
    case ESP_RST_SW:       return "sw";
    case ESP_RST_PANIC:    return "panic";
    case ESP_RST_INT_WDT:  return "int-wdt";
    case ESP_RST_TASK_WDT: return "task-wdt";
    case ESP_RST_WDT:      return "wdt";
    case ESP_RST_DEEPSLEEP:return "deepsleep";
    case ESP_RST_BROWNOUT: return "brownout";
    case ESP_RST_SDIO:     return "sdio";
    default:               return "unknown";
  }
}

static void publishTelemetry() {
  if (!telemetryChar) return;
  String ip = (WiFi.status() == WL_CONNECTED) ? WiFi.localIP().toString() : "";
  String t = "{\"uptime_ms\":" + String((unsigned long)millis())
           + ",\"free_heap\":" + String((unsigned long)esp_get_free_heap_size())
           + ",\"free_psram\":" + String((unsigned long)heap_caps_get_free_size(MALLOC_CAP_SPIRAM))
           + ",\"reset_reason\":\"" + String(resetReasonLabel(esp_reset_reason())) + "\""
           + ",\"sha\":\"" GIT_SHA "\"";
  if (ip.length()) t += ",\"ip\":\"" + ip + "\"";
  t += "}";
  telemetryChar->setValue(t.c_str());
  if (bleServiceStarted) telemetryChar->notify();
}

void loop() {
  if (otaRestartPending) {
    delay(500);  // let the last notify + ATT response land
    ESP.restart();
  }

  if (millis() - lastTelemetryAt > TELEMETRY_INTERVAL_MS) {
    publishTelemetry();
    lastTelemetryAt = millis();
  }

  if ((motorLeft != 0 || motorRight != 0)
      && motorLastWriteAt > 0
      && millis() - motorLastWriteAt > MOTOR_WATCHDOG_MS) {
    applyMotors(0, 0);
    Serial.printf("motor watchdog: stopped\n");
  }

  // LLM pulse auto-stop. Only fires if we're still the active pulse; a
  // newer joystick write or pulse would have bumped motorPulseId and
  // invalidated this end-time.
  if (motorPulseEndAt > 0
      && motorActivePulseId == motorPulseId
      && millis() >= motorPulseEndAt) {
    applyMotors(0, 0);
    motorPulseEndAt = 0;
    Serial.printf("motor pulse ended\n");
  }

  if (wifiPhase == PHASE_SCANNING) {
    int n = WiFi.scanComplete();
    if (n >= 0 || n == WIFI_SCAN_FAILED) {
      Serial.printf("wifi scan complete: n=%d after %lu ms\n", n, millis() - scanStartedAt);
      if (n >= 0) {
        publishScan();
      } else if (wifiScanChar) {
        // WIFI_SCAN_FAILED — notify empty so the dashboard clears its
        // "scanning…" spinner promptly instead of waiting for its own
        // 20s failsafe.
        wifiScanChar->setValue((uint8_t*)"[]", 2);
        wifiScanChar->notify();
      }
      wifiPhase = PHASE_IDLE;
    } else if (millis() - scanStartedAt > 30000) {
      // Failsafe: classic ESP32 with BLE active occasionally never reports
      // scan-complete. Don't leave the state machine wedged forever.
      // 30s covers the slower passive-scan path.
      Serial.printf("wifi scan abandoned after 30s (n=%d) — releasing state\n", n);
      WiFi.scanDelete();
      wifiPhase = PHASE_IDLE;
      // Publish empty list so the dashboard's notify listener clears its
      // "scanning…" UI rather than waiting for its own 20s timeout.
      if (wifiScanChar) {
        wifiScanChar->setValue((uint8_t*)"[]", 2);
        wifiScanChar->notify();
      }
    }
  } else if (wifiPhase == PHASE_JOINING) {
    wl_status_t s = WiFi.status();
    if (s == WL_CONNECTED) {
      wifiPhase = PHASE_IDLE;
      prefs.begin("wifi", false);
      prefs.putString("ssid", pendingSsid);
      prefs.putString("pass", pendingPass);
      prefs.end();
      // IP is what the dashboard needs to open the MJPEG stream. Surface it
      // on wifi-status (notify) so a later-attached dashboard picks it up.
      publishStatus("joined", pendingSsid, "", WiFi.localIP().toString());
      if (cameraReady) startCameraServer();
    } else if (s == WL_NO_SSID_AVAIL || s == WL_CONNECT_FAILED ||
               millis() - joinStartedAt > JOIN_TIMEOUT_MS) {
      wifiPhase = PHASE_IDLE;
      const char* err = (s == WL_NO_SSID_AVAIL) ? "ssid not found"
                      : (s == WL_CONNECT_FAILED) ? "connect failed"
                      : "timeout";
      WiFi.disconnect(true, false);
      publishStatus("failed", pendingSsid, err);
    }
  }
  delay(100);
}
