// Better Robotics — robot firmware. Mirrors firmware/pi_robot/pi_robot.py.
// LED_PIN defaults to the red LED on ESP32-CAM-MB (GPIO 33, active-low).

// NimBLE-Arduino (h2zero, 2.5.0) replaces Arduino's built-in Bluedroid
// BLEDevice API. BLE* aliases still resolve to NimBLE* classes so most
// call sites are unchanged. Property constants are NIMBLE_PROPERTY::*,
// CCCDs auto-register (no more BLE2902), createService allocates handles
// dynamically (no budget). 2.x callback signatures add NimBLEConnInfo&
// (and int reason for onDisconnect). Reclaims ~58 KB of internal DRAM on
// classic ESP32-CAM — heap 19→77 KB, largest DMA block 7→70 KB at end of
// setup — so WiFi init gets all 4 RX buffers instead of starving out.
// 1.4.x aborts esp_bt_controller_init with ESP_ERR_INVALID_STATE on
// arduino-esp32 3.x (IDF 5.x); 2.x is the IDF-5-native line.
#include <NimBLEDevice.h>
#include <WiFi.h>
#include <ESPmDNS.h>
#include <Preferences.h>
#include <Update.h>
#include <esp_heap_caps.h>
#include <esp_wifi.h>
#include "esp_camera.h"
#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"
#include "version.h"  // generated by `make compile`: #define GIT_SHA "abc12345"

// AI-Thinker ESP32-CAM pin map. Matches the OV2640/OV3660/OV5640 socket on
// the standard AI-Thinker board (the one paired with CAM-MB). If a future
// board variant shows up, switch on an ifdef rather than patching in place.
#define PWDN_GPIO_NUM     32
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM      0
#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27
#define Y9_GPIO_NUM       35
#define Y8_GPIO_NUM       34
#define Y7_GPIO_NUM       39
#define Y6_GPIO_NUM       36
#define Y5_GPIO_NUM       21
#define Y4_GPIO_NUM       19
#define Y3_GPIO_NUM       18
#define Y2_GPIO_NUM        5
#define VSYNC_GPIO_NUM    25
#define HREF_GPIO_NUM     23
#define PCLK_GPIO_NUM     22

// UUIDs are generated from protocol/uuids.json — see tools/gen-uuids.py.
// Adding a new BLE characteristic = edit the JSON, run `make gen-uuids`,
// rebuild. Both this firmware AND the Pi firmware AND the dashboard pull
// from the same source so a typo in one place can't silently desync the
// protocol.
#include "uuids.h"

// Motor watchdog: every write resets the timer; silence reverts to (0, 0).
// Safe default on disconnect — no redundant channel required.
const unsigned long MOTOR_WATCHDOG_MS = 500;

// Control-loop invariants — see .claude/CLAUDE.md. LLM-issued motion is a
// 4-byte motor-char payload [l, r, dur_hi, dur_lo] that the firmware auto-
// stops after dur_ms. Magnitude + duration are clamped to these caps
// regardless of what the dashboard sent; firmware is the safety floor,
// not Pip / Claude.
const int8_t  LLM_MAX_SPEED        = 40;
const uint16_t LLM_MAX_DURATION_MS = 2000;

// Shared BLE OTA protocol (matches firmware/pi_robot/pi_robot.py):
//   ota-data   (write)    — binary frames with 1-byte opcode:
//       0x00                 abort — drop any in-flight Update state
//       0x01 [size:u32 BE]   begin-stream — reset, expect `size` bytes over BLE
//       0x02 [payload]       chunk — append to flash
//       0x03                 commit — finalize OTA + restart
//       0x04 [json]          fetch-url — accepted wire-wise, replies "failed"
//                            in this build. HTTPClient + NetworkClientSecure
//                            + mbedTLS were cut to fit IRAM once camera libs
//                            landed; dashboard's grace-window logic then falls
//                            back to BLE-stream OTA (slower, same result).
//   ota-status (read+notify) — UTF-8 JSON: {"st":...,"n":...,"total":...,"err":...}
//   fw-info    (read)     — UTF-8 JSON: {"type":"esp32","url":"firmware/bins/esp32_robot.bin"}
// The dashboard reads fw-info to know where to fetch the update binary from.

// Shared BLE WiFi spec (matches firmware/pi_robot/pi_robot.py):
//   wifi-scan   — read + notify. UTF-8 JSON: [{"s":ssid,"r":0..100,"p":0|1}].
//                 Reading triggers a rescan; notify fires when done. Strongest first.
//   wifi-join   — write. UTF-8 JSON: {"s":ssid,"p":password}. Empty p for open nets.
//   wifi-status — read + notify. UTF-8 JSON: {"st":state,"ssid":name,"err":msg}.
//                 States: idle, joining, joined, failed. (Scan activity is
//                 tracked client-side via wifi-scan notifications; it doesn't
//                 change connection state.)

// Pin configuration — runtime overrides loaded from NVS Preferences ("pins"
// namespace) at boot, mirroring the Pi's pi-robot.conf shape. Compile-time
// values are the safe defaults for ESP32-CAM-MB:
//
//   LED_PIN     = 33 → red status LED on the AI-Thinker module
//   FLASH_PIN   = 4  → white flash LED on the AI-Thinker module (PWM 0..100)
//   motors      = {l: in1=14, in2=15, r: in1=13, in2=12}
//
// Pin allocation reality on this chip is brutal. The camera consumes 15
// GPIOs; what's left:
//   - 13, 14, 15: SD card data pins, free when SD is unused. SAFE.
//   - 4:  white flash LED. Now reserved for FLASH_PIN so the LED is
//         independently controllable instead of flickering with motor PWM.
//   - 2, 12: strap pins. GPIO 12 must be LOW at boot for 3.3V flash
//         voltage. The L298N's IN pins are typically high-impedance CMOS
//         (no internal pull-up on the common blue board), so GPIO 12
//         stays LOW at boot via internal pull-down — safe. If your
//         specific L298N has an internal pull-up on IN3, the chip won't
//         boot (symptom: continuous `ets Jul 29` in serial); fix is one
//         external 10k pull-down from GPIO 12 to GND.
//   - 16: PSRAM CS / UART2_RXD on some AI-Thinker revisions. PSRAM is
//         active (psram=1 in fw-info); avoid.
//
// ENA/ENB jumpers on the L298N stay ON (5V — H-bridge always enabled),
// PWM rides the IN pins. Forward = IN1=PWM, IN2=LOW; reverse = IN1=LOW,
// IN2=PWM. Same 2-pin-per-motor pattern the Pi uses.
int LED_PIN = 33;
int FLASH_PIN = 4;
int MOTOR_L_IN1 = 14;
int MOTOR_L_IN2 = 15;
int MOTOR_R_IN1 = 13;
int MOTOR_R_IN2 = 12;
// LEDC PWM config for the H-bridge inputs. 1 kHz keeps motor whine
// inaudible without the L298N's input filtering struggling. 8-bit = duty
// in [0..255] from a signed [-100..100] input.
static const uint32_t MOTOR_PWM_FREQ = 1000;
static const uint8_t  MOTOR_PWM_RES  = 8;
static bool _motors_attached = false;

const size_t SCAN_MAX = 10;

// Set in setup() once the chip-id-derived name is built; used by BLE
// advertising, mDNS service publishing, and serial diagnostics. File-scope
// so the mDNS startup can read it without a parameter wedge.
static char robotName[32] = "BR-XXXX";

BLECharacteristic* ledChar        = nullptr;
BLECharacteristic* wifiScanChar   = nullptr;
BLECharacteristic* wifiJoinChar   = nullptr;
BLECharacteristic* wifiStatusChar = nullptr;
BLECharacteristic* telemetryChar  = nullptr;
static unsigned long lastTelemetryAt = 0;
static const unsigned long TELEMETRY_INTERVAL_MS = 10000;

BLECharacteristic* snapshotRequestChar = nullptr;
BLECharacteristic* snapshotDataChar    = nullptr;
BLECharacteristic* cameraProfileChar   = nullptr;
static TaskHandle_t snapshotTaskHandle = nullptr;

// Camera profile — three discrete operating points the user can pick.
// Persisted to Preferences ("cam"/"profile"); applied at initCamera time.
// Compact saves DMA heap (matters when WiFi is marginal); full pushes
// resolution at the cost of buffers + bandwidth. Standard is the default.
enum CamProfile { CAM_COMPACT = 0, CAM_STANDARD = 1, CAM_FULL = 2 };
static CamProfile cameraProfile = CAM_COMPACT;
static const char* cameraProfileName(CamProfile p) {
  switch (p) {
    case CAM_COMPACT:  return "compact";
    case CAM_STANDARD: return "standard";
    case CAM_FULL:     return "full";
  }
  return "standard";
}
static CamProfile cameraProfileFromName(const String& s) {
  if (s == "compact")  return CAM_COMPACT;
  if (s == "full")     return CAM_FULL;
  return CAM_STANDARD;
}
// Snapshot chunk size — must fit under MTU-3. Matches public/ble.js CHUNK_BYTES
// (180), which is conservative for desktop Chrome's negotiated MTU (~185).
static const size_t SNAPSHOT_CHUNK_BYTES = 180;
BLECharacteristic* otaDataChar    = nullptr;
BLECharacteristic* otaStatusChar  = nullptr;
BLECharacteristic* fwInfoChar     = nullptr;
BLECharacteristic* motorChar      = nullptr;
BLECharacteristic* flashChar      = nullptr;
BLECharacteristic* pinConfigChar  = nullptr;
static uint8_t flashLevel = 0;  // 0..100 — current PWM brightness
static bool _flash_attached = false;
// Set by PinConfigCallbacks::onWrite after a valid pin update lands; loop()
// reboots so the new pins take effect on next boot. Same shape as
// otaRestartPending.
static bool pinConfigRestartPending = false;

int8_t motorLeft = 0;
int8_t motorRight = 0;
unsigned long motorLastWriteAt = 0;
// Active pulse tracking — LLM 4-byte writes set motorPulseEndAt; loop()
// stops motors when millis() passes it. motorPulseId is bumped by every
// motor write so a joystick or newer pulse invalidates the earlier one's
// end-time check (newer write always wins).
uint32_t motorPulseId = 0;
uint32_t motorActivePulseId = 0;
unsigned long motorPulseEndAt = 0;

bool otaInProgress = false;
size_t otaExpected = 0;
size_t otaReceived = 0;
// Restart is deferred out of the BLE write callback so the ATT response
// for the commit opcode (0x03) can be sent before we reboot. Restarting
// inline makes the client see "GATT operation failed" even though the
// flash commit succeeded.
volatile bool otaRestartPending = false;

Preferences prefs;

bool ledOn = false;

static bool cameraReady = false;
static int  cameraInitError = 0;  // 0 if no init attempted or success
static TaskHandle_t streamTaskHandle = nullptr;
// fw-info notify asserts (getService() != nullptr) if called before
// service->start() — the first publish in setup() happens pre-start, so gate
// notifies until the service is live.
static bool bleServiceStarted = false;

// WiFi state machine — non-blocking, polled from loop().
enum WifiPhase { PHASE_IDLE, PHASE_SCANNING, PHASE_JOINING };
WifiPhase wifiPhase = PHASE_IDLE;
String pendingSsid;
String pendingPass;
unsigned long joinStartedAt = 0;
const unsigned long JOIN_TIMEOUT_MS = 20000;

static String jsonEscape(const String& s) {
  String out; out.reserve(s.length() + 2);
  for (size_t i = 0; i < s.length(); i++) {
    char c = s[i];
    if (c == '"' || c == '\\') { out += '\\'; out += c; }
    else if (c == '\n')        { out += "\\n"; }
    else if (c == '\r')        { out += "\\r"; }
    else if ((uint8_t)c < 0x20){ /* drop control chars */ }
    else                       { out += c; }
  }
  return out;
}

static int rssiToStrength(int rssi) {
  // Map -100..-50 dBm → 0..100.
  int s = (rssi + 100) * 2;
  if (s < 0) s = 0;
  if (s > 100) s = 100;
  return s;
}

static void publishStatus(const char* st, const String& ssid = "", const String& err = "", const String& ip = "") {
  String payload = "{\"st\":\""; payload += st; payload += "\"";
  if (ssid.length()) { payload += ",\"ssid\":\""; payload += jsonEscape(ssid); payload += "\""; }
  if (err.length())  { payload += ",\"err\":\"";  payload += jsonEscape(err);  payload += "\""; }
  if (ip.length())   { payload += ",\"ip\":\"";   payload += ip;               payload += "\""; }
  payload += "}";
  if (wifiStatusChar) {
    wifiStatusChar->setValue((uint8_t*)payload.c_str(), payload.length());
    wifiStatusChar->notify();
  }
  Serial.printf("wifi-status → %s\n", payload.c_str());
}

static void publishScan() {
  int n = WiFi.scanComplete();
  if (n < 0) n = 0;

  int idx[32];
  int count = min(n, 32);
  for (int i = 0; i < count; i++) idx[i] = i;
  for (int i = 0; i < count - 1; i++) {
    for (int j = i + 1; j < count; j++) {
      if (WiFi.RSSI(idx[j]) > WiFi.RSSI(idx[i])) { int t = idx[i]; idx[i] = idx[j]; idx[j] = t; }
    }
  }

  String payload = "[";
  size_t emitted = 0;
  String seen;
  for (int k = 0; k < count && emitted < SCAN_MAX; k++) {
    String ssid = WiFi.SSID(idx[k]);
    if (ssid.length() == 0) continue;
    String key = "\x01" + ssid + "\x01";
    if (seen.indexOf(key) >= 0) continue;
    seen += key;
    int strength = rssiToStrength(WiFi.RSSI(idx[k]));
    int secured = (WiFi.encryptionType(idx[k]) == WIFI_AUTH_OPEN) ? 0 : 1;
    if (ssid.length() > 32) ssid = ssid.substring(0, 32);
    if (emitted) payload += ",";
    payload += "{\"s\":\""; payload += jsonEscape(ssid); payload += "\"";
    payload += ",\"r\":"; payload += strength;
    payload += ",\"p\":"; payload += secured;
    payload += "}";
    emitted++;
  }
  payload += "]";
  if (wifiScanChar) {
    wifiScanChar->setValue((uint8_t*)payload.c_str(), payload.length());
    wifiScanChar->notify();
  }
  WiFi.scanDelete();
}

static unsigned long scanStartedAt = 0;
static void startScan() {
  if (wifiPhase != PHASE_IDLE) {
    Serial.printf("scan ignored — wifiPhase=%d (busy)\n", (int)wifiPhase);
    return;
  }
  // Make sure STA mode is live. Something (camera init, join-then-failed,
  // etc.) may have toggled it since boot; scan on the wrong mode returns 0.
  if (WiFi.getMode() != WIFI_STA) {
    WiFi.mode(WIFI_STA);
    delay(20);
  }
  WiFi.scanDelete();
  // Passive scan (listen for beacons, don't emit probe requests) with
  // 500ms per channel. On classic ESP32 with BLE active, the two radios
  // time-share 2.4 GHz so aggressively that active scans drop most probe
  // responses — zero APs seen. Passive + longer dwell lets WiFi catch
  // enough beacon frames to enumerate the neighborhood. Slower (~7-12s
  // vs 3-5s active) but actually works.
  //   scanNetworks(async, show_hidden, passive, max_ms_per_chan, channel)
  int rc = WiFi.scanNetworks(true, false, true, 500);
  wifiPhase = PHASE_SCANNING;
  scanStartedAt = millis();
  Serial.printf("wifi scan started (passive, rc=%d, mode=%d, sleep=%d, free heap=%u)\n",
                rc, (int)WiFi.getMode(), (int)WiFi.getSleep(), ESP.getFreeHeap());
}

static void startJoin(const String& ssid, const String& pass) {
  pendingSsid = ssid;
  pendingPass = pass;
  wifiPhase = PHASE_JOINING;
  joinStartedAt = millis();
  // No explicit disconnect — WiFi.begin() calls esp_wifi_connect() which
  // drops any existing association internally. Calling disconnect(false,...)
  // here races with the WiFi task's internal queues and asserts; calling
  // disconnect(true,...) deinits the driver and forces wifi_init to
  // re-allocate 4 RX buffers on a fragmented heap (BLE + camera have since
  // claimed DRAM) and fails.
  WiFi.begin(ssid.c_str(), pass.c_str());
  publishStatus("joining", ssid);
}

static bool initCamera() {
  camera_config_t config = {};
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer   = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk     = XCLK_GPIO_NUM;
  config.pin_pclk     = PCLK_GPIO_NUM;
  config.pin_vsync    = VSYNC_GPIO_NUM;
  config.pin_href     = HREF_GPIO_NUM;
  config.pin_sccb_sda = SIOD_GPIO_NUM;
  config.pin_sccb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn     = PWDN_GPIO_NUM;
  config.pin_reset    = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_JPEG;
  // Profile-driven framesize / quality. fb_count stays 1 regardless —
  // double-buffering costs ~10 KB of DRAM in driver state and buys nothing
  // at our stream rates. Full pushes 2 only when PSRAM is present.
  switch (cameraProfile) {
    case CAM_COMPACT:
      config.frame_size = FRAMESIZE_QVGA;  // 320×240
      config.jpeg_quality = 15;
      config.fb_count = 1;
      break;
    case CAM_FULL:
      config.frame_size = FRAMESIZE_SVGA;  // 800×600
      config.jpeg_quality = 10;
      config.fb_count = psramFound() ? 2 : 1;
      break;
    case CAM_STANDARD:
    default:
      config.frame_size = FRAMESIZE_VGA;   // 640×480 — preserves prior default.
      config.jpeg_quality = 12;
      // PSRAM-backed double-buffer: capture frame N+1 while transmitting
      // frame N. ~75 KB PSRAM (free; nothing else uses it) buys a smoother
      // snapshot/stream — single-buffer with GRAB_LATEST forces a full
      // capture round-trip per fb_get(), causing ~100-200 ms hitches.
      config.fb_count = psramFound() ? 2 : 1;
      break;
  }
  config.fb_location  = psramFound() ? CAMERA_FB_IN_PSRAM : CAMERA_FB_IN_DRAM;
  config.grab_mode    = CAMERA_GRAB_LATEST;
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    cameraInitError = (int)err;
    Serial.printf("camera init failed: 0x%x (psram=%d, profile=%s)\n",
                  err, psramFound(), cameraProfileName(cameraProfile));
    return false;
  }
  Serial.printf("camera ok, psram=%d, profile=%s\n",
                psramFound(), cameraProfileName(cameraProfile));
  // Orientation + cosmetic-only sensor tuning. EXPOSURE tweaks
  // (set_aec2, set_gainceiling, set_awb_gain) broke OV2640 on this die
  // revision earlier (all-black frames) — those touch the AEC pipeline
  // and stay reverted. brightness / saturation / contrast / sharpness
  // are post-DSP cosmetic knobs that don't reconfigure exposure; safe
  // to apply, and the factory defaults read flat indoors.
  // vflip + hmirror handle the AI-Thinker mounting quirk (the camera
  // connector exits the module in a way that produces a 180°-rotated
  // image vs. how operators hold the chassis).
  sensor_t* s = esp_camera_sensor_get();
  if (s) {
    s->set_vflip(s, 1);
    s->set_hmirror(s, 1);
    s->set_brightness(s, 1);   // -2..2; lifts dim indoor scenes
    s->set_saturation(s, 1);   // -2..2; default reads washed-out
    s->set_contrast(s, 1);     // -2..2; default reads flat
    s->set_sharpness(s, 1);    // -2..2; +1 cleans up VLM/detector input
    // Disable AWB *gain recompute* — keeps white-balance auto-mode on so
    // a real lighting change still adapts, but stops the per-frame gain
    // hunting that produces visible color-cast pulsing on a static scene.
    // NOT the same call that broke the OV2640 earlier — that was
    // set_awb_gain(s, 1) which TURNS the recompute on. The 0 value is the
    // opposite operation; should be safe on the picky die.
    s->set_awb_gain(s, 0);
  }
  return true;
}

// MJPEG over HTTP — raw WiFiServer in a FreeRTOS task. Picked over
// esp_http_server because the latter's IRAM footprint pushed us 1952 B over
// iram0_0_seg. This variant only pulls in LwIP + JPEG dataflow (camera
// driver already resident) and holds up fine for classroom-distance streams.
// Also serves POST /ota (WiFi OTA upload) + OPTIONS /ota (PNA preflight) so
// the dashboard can push firmware over the LAN when it has IP + PNA access.
static void streamTask(void* param) {
  WiFiServer server(81);
  server.begin();
  Serial.println("HTTP task ready on :81 (/stream, /ota)");
  while (true) {
    WiFiClient client = server.accept();
    if (!client) { vTaskDelay(50 / portTICK_PERIOD_MS); continue; }
    client.setNoDelay(true);

    // Request-line + header parse. Cap total header read at 2 s to avoid
    // parking the task on a half-open connection.
    String method, path;
    long contentLength = -1;
    String origin;        // echoed back when present (some browsers care)
    bool   pnaRequested = false;
    {
      unsigned long headerStart = millis();
      String reqLine = client.readStringUntil('\n');
      int sp1 = reqLine.indexOf(' ');
      int sp2 = (sp1 >= 0) ? reqLine.indexOf(' ', sp1 + 1) : -1;
      if (sp1 > 0 && sp2 > sp1) {
        method = reqLine.substring(0, sp1);
        path   = reqLine.substring(sp1 + 1, sp2);
      }
      while (client.connected() && millis() - headerStart < 2000) {
        String line = client.readStringUntil('\n');
        // Trim trailing \r.
        if (line.length() && line[line.length() - 1] == '\r') line.remove(line.length() - 1);
        if (line.length() == 0) break;  // end of headers
        int colon = line.indexOf(':');
        if (colon <= 0) continue;
        String key = line.substring(0, colon);
        String val = line.substring(colon + 1);
        while (val.length() && (val[0] == ' ' || val[0] == '\t')) val.remove(0, 1);
        // Case-insensitive compare — browsers may send any casing.
        if (key.equalsIgnoreCase("Content-Length")) {
          contentLength = val.toInt();
        } else if (key.equalsIgnoreCase("Origin")) {
          origin = val;
        } else if (key.equalsIgnoreCase("Access-Control-Request-Private-Network")) {
          pnaRequested = val.equalsIgnoreCase("true");
        }
      }
    }

    // Modern Chrome (M130+) tightened PNA: when the page is on
    // https://<github-pages-or-similar> and the target is http://<private-IP>,
    // the preflight expects Access-Control-Allow-Origin to *echo the
    // requesting Origin* rather than `*`. With `*` the browser rejects the
    // preflight and the POST never reaches us — symptom: "Failed to fetch"
    // in the dashboard log, with no entry in the /ota handler. Echoing the
    // origin (and adding Vary: Origin so caches don't blow up) restores it.
    String acOrigin = origin.length() ? ("Access-Control-Allow-Origin: " + origin + "\r\nVary: Origin\r\n")
                                      : "Access-Control-Allow-Origin: *\r\n";

    if (method == "OPTIONS" && (path == "/ota" || path == "/health")) {
      // PNA preflight — Chrome sends this before cross-origin → private-IP
      // POSTs (and GETs to private IPs with the PNA flag). Max-Age=86400
      // caches it for a day so repeat OTAs / health probes skip it.
      client.print("HTTP/1.1 204 No Content\r\n");
      client.print(acOrigin);
      client.print("Access-Control-Allow-Methods: GET, POST, OPTIONS\r\n"
                   "Access-Control-Allow-Headers: Content-Type\r\n"
                   "Access-Control-Allow-Private-Network: true\r\n"
                   "Access-Control-Max-Age: 86400\r\n"
                   "Content-Length: 0\r\n"
                   "Connection: close\r\n\r\n");
      (void)pnaRequested;  // reserved for stricter replies
      client.stop();
      continue;
    }

    if (method == "POST" && path == "/ota") {
      // Guard both bad (missing/negative) and oversized uploads — 4 MB cap
      // matches the app0 partition ceiling on min_spiffs.
      if (contentLength <= 0 || contentLength > 4 * 1024 * 1024) {
        client.print("HTTP/1.1 400 Bad Request\r\n");
        client.print(acOrigin);
        client.print("Content-Length: 0\r\nConnection: close\r\n\r\n");
        client.stop();
        continue;
      }
      if (!Update.begin((size_t)contentLength)) {
        client.print("HTTP/1.1 500 Internal Server Error\r\n");
        client.print(acOrigin);
        client.print("Content-Length: 0\r\nConnection: close\r\n\r\n");
        client.stop();
        continue;
      }
      uint8_t buf[2048];
      size_t received = 0;
      unsigned long lastData = millis();
      bool failed = false;
      while (received < (size_t)contentLength) {
        int avail = client.available();
        if (avail <= 0) {
          if (!client.connected()) { failed = true; break; }
          // 10 s stall timeout — abort instead of hanging the task.
          if (millis() - lastData > 10000) { failed = true; break; }
          // vTaskDelay(1) = one tick = 10 ms minimum on FreeRTOS's 10 ms tick.
          // The previous form `vTaskDelay(5 / portTICK_PERIOD_MS)` evaluated
          // to vTaskDelay(0) (5/10 = 0 integer division) which is a no-op —
          // when the TCP RX buffer was empty the loop spun at 100% CPU on
          // core 1, IDLE on that core never ran, and IDLE-WDT reset the
          // chip mid-upload. Symptom in dashboard log: orphaned OTA state
          // around 5% as the upload died and the chip rejoined WiFi.
          vTaskDelay(1);
          continue;
        }
        size_t want = sizeof(buf);
        size_t remaining = (size_t)contentLength - received;
        if (want > remaining) want = remaining;
        int got = client.read(buf, want);
        if (got <= 0) {
          if (millis() - lastData > 10000) { failed = true; break; }
          continue;
        }
        if (Update.write(buf, got) != (size_t)got) { failed = true; break; }
        received += got;
        lastData = millis();
      }
      if (failed) {
        Update.abort();
        client.print("HTTP/1.1 500 Internal Server Error\r\n");
        client.print(acOrigin);
        client.print("Content-Length: 0\r\nConnection: close\r\n\r\n");
        client.stop();
        continue;
      }
      if (!Update.end(true)) {
        client.print("HTTP/1.1 500 Internal Server Error\r\n");
        client.print(acOrigin);
        client.print("Content-Length: 0\r\nConnection: close\r\n\r\n");
        client.stop();
        continue;
      }
      client.print("HTTP/1.1 200 OK\r\n");
      client.print(acOrigin);
      client.print("Content-Type: text/plain\r\n"
                   "Content-Length: 2\r\n"
                   "Connection: close\r\n\r\n"
                   "OK");
      client.stop();
      // Defer restart to loop() — gives TCP FIN time to flush, matches how
      // the BLE commit path already reboots.
      otaRestartPending = true;
      continue;
    }

    if (method == "GET" && path == "/stream") {
      // CORS open so the dashboard on GitHub Pages can load the stream as <img>.
      client.print("HTTP/1.1 200 OK\r\n"
                   "Content-Type: multipart/x-mixed-replace;boundary=frame\r\n"
                   "Access-Control-Allow-Origin: *\r\n"
                   "Connection: close\r\n\r\n");
      while (client.connected()) {
        camera_fb_t *fb = esp_camera_fb_get();
        if (!fb) break;
        client.printf("\r\n--frame\r\nContent-Type: image/jpeg\r\nContent-Length: %u\r\n\r\n", fb->len);
        // Chunked write feeds the IDLE task so the watchdog doesn't trip
        // during a long write on degraded WiFi (1-of-4 RX buffers under BLE
        // coexistence). One yield per frame is enough on FreeRTOS's 10 ms
        // tick — vTaskDelay(1) is *at least* 10 ms, so per-1KB-chunk yields
        // capped framerate at ~10 fps for typical 10 KB JPEGs (10 chunks ×
        // 10 ms = 100 ms/frame). 4 KB chunks fit the lwIP TX buffer and
        // keep the cooperative-yield budget bounded.
        size_t total = 0;
        const size_t WRITE_CHUNK = 4096;
        bool ok = true;
        while (total < fb->len) {
          size_t take = fb->len - total;
          if (take > WRITE_CHUNK) take = WRITE_CHUNK;
          size_t w = client.write(fb->buf + total, take);
          if (w != take) { ok = false; break; }
          total += w;
        }
        esp_camera_fb_return(fb);
        if (!ok) break;
        // One explicit yield per frame — fed IDLE so IDLE-WDT can't fire
        // even when esp_camera_fb_get returns immediately (camera DMA
        // double-buffered → frame already ready) AND client.write fits
        // entirely in the lwIP TX buffer (no TCP backpressure). Removing
        // this yield wedged the stream on iPhone hotspot — natural
        // BLOCKED states aren't guaranteed under all network conditions.
        // 10 ms cost per frame is comfortably under the 67 ms practical
        // budget at 15 fps, well worth the determinism.
        vTaskDelay(1);
      }
      client.stop();
      continue;
    }

    if (method == "GET" && path == "/health") {
      // Dashboard's presence-plane probe target. Same body shape as the Pi
      // /health endpoint so the dashboard doesn't need per-tier handling.
      // CORS open so the HTTPS dashboard can fetch from this private IP.
      String body = "{\"ok\":true,\"type\":\"esp32\",\"robotId\":\"";
      body += robotName;
      body += "\",\"ip\":\"";
      body += WiFi.localIP().toString();
      body += "\",\"uptime_s\":";
      body += millis() / 1000;
      body += "}";
      client.print("HTTP/1.1 200 OK\r\n"
                   "Access-Control-Allow-Origin: *\r\n"
                   "Content-Type: application/json\r\n");
      client.printf("Content-Length: %u\r\n", body.length());
      client.print("Connection: close\r\n\r\n");
      client.print(body);
      client.stop();
      continue;
    }

    client.print("HTTP/1.1 404 Not Found\r\n"
                 "Access-Control-Allow-Origin: *\r\n"
                 "Content-Length: 0\r\n"
                 "Connection: close\r\n\r\n");
    client.stop();
  }
}

static void startCameraServer() {
  if (streamTaskHandle) return;
  // Pin to core 1 — core 0 runs WiFi + BLE stacks; keep them uncontested.
  // 8 KB stack — 4 KB was bumping into watchdog territory under sustained
  // streaming. lwIP's TCP send eats stack from the calling task; headroom
  // prevents a canary smash dovetailing with the watchdog case.
  xTaskCreatePinnedToCore(streamTask, "mjpeg", 8192, nullptr, 1, &streamTaskHandle, 1);
}

static void publishFwInfo() {
  if (!fwInfoChar) return;
  // Always advertise the non-camera caps so the dashboard renders LED /
  // motors / wifi UI even when the camera failed to init. Each cap maps to
  // an existing BLE characteristic via the dashboard's UUIDS_BY_CAP table.
  String info = "{\"type\":\"esp32\",\"url\":\"firmware/bins/esp32_robot.bin\"";
  // `version` field matches the Pi's fw-info shape so the dashboard's menu
  // Git SHA stamped into firmware/esp32_robot/version.h by `make compile`;
  // matches the Pi's version.py convention so fw-info.version is symmetric
  // across platforms. "dev" when building outside git (rare — CI always has git).
  info += ",\"version\":\"" GIT_SHA "\"";
  info += ",\"caps\":[";
  info += "{\"name\":\"led\",\"type\":\"toggle\",\"pin\":";
  info += String(LED_PIN);
  info += "}";
  if (_flash_attached) {
    info += ",{\"name\":\"flash\",\"type\":\"level\",\"range\":[0,100],\"pin\":";
    info += String(FLASH_PIN);
    info += "}";
  }
  info += ",{\"name\":\"wifi\",\"type\":\"wifi-scan\"}";
  // Motor pin assignments mirror Pi's get-config shape so the future
  // pinout editor (working.md item D) can render both platforms with
  // one schema. ENA/ENB jumpers stay ON — H-bridge is always enabled,
  // PWM rides the IN pins. See firmware comments above LED_PIN decl.
  info += ",{\"name\":\"motors\",\"type\":\"signed-pair\",\"range\":[-100,100]";
  info += ",\"pins\":{\"left\":{\"in1\":";
  info += String(MOTOR_L_IN1);
  info += ",\"in2\":";
  info += String(MOTOR_L_IN2);
  info += "},\"right\":{\"in1\":";
  info += String(MOTOR_R_IN1);
  info += ",\"in2\":";
  info += String(MOTOR_R_IN2);
  info += "}}}";
  if (cameraReady) {
    info += ",{\"name\":\"camera\",\"type\":\"mjpeg-stream\",\"port\":81,\"path\":\"/stream\"";
    // Profile metadata so the dashboard can render the picker. `profile`
    // is the current one; `profiles` is the menu of options to offer.
    info += ",\"profile\":\"";
    info += cameraProfileName(cameraProfile);
    info += "\",\"profiles\":[\"compact\",\"standard\",\"full\"]}";
    // Snapshot is BLE-only and works without WiFi — distinct cap so the
    // dashboard can render it independently of the live-stream card.
    info += ",{\"name\":\"snapshot\",\"type\":\"ble-snapshot\"}";
  }
  info += "]";
  if (!cameraReady && cameraInitError) {
    info += ",\"camera_err\":";
    info += String(cameraInitError);
  }
  info += "}";
  fwInfoChar->setValue(info.c_str());
  // Notify only once the service is live — pre-start notify() asserts. After
  // service->start(), this pushes schema changes (camera cap appearing post-
  // WiFi-join) to any subscribed dashboard.
  if (bleServiceStarted) fwInfoChar->notify();
}

static void applyLed(bool on) {
  ledOn = on;
  digitalWrite(LED_PIN, on ? LOW : HIGH);  // active-low
  uint8_t v = on ? 1 : 0;
  if (ledChar) {
    ledChar->setValue(&v, 1);
    ledChar->notify();
  }
}

static void publishOta(const char* st, size_t n = 0, size_t total = 0, const char* err = nullptr) {
  String payload = "{\"st\":\""; payload += st; payload += "\"";
  payload += ",\"n\":"; payload += (unsigned)n;
  if (total) { payload += ",\"total\":"; payload += (unsigned)total; }
  if (err)   { payload += ",\"err\":\""; payload += err; payload += "\""; }
  payload += "}";
  if (otaStatusChar) {
    otaStatusChar->setValue((uint8_t*)payload.c_str(), payload.length());
    otaStatusChar->notify();
  }
  Serial.printf("ota-status → %s\n", payload.c_str());
}

// Rate-limit state for op 0x02 chunk-receive notifies. Reset on op 0x01.
static size_t        chunkLastReported = 0;
static unsigned long chunkLastProgress = 0;

class OtaDataCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch, NimBLEConnInfo& /*info*/) override {
    // std::string (not Arduino String) — OTA chunks are raw bytes with
    // embedded nulls. String(const char*) would truncate at the first \0.
    std::string v = ch->getValue();
    if (v.length() == 0) return;
    uint8_t op = (uint8_t)v[0];
    if (op == 0x00) {
      if (otaInProgress) {
        Update.abort();
        otaInProgress = false;
      }
      otaReceived = 0;
      otaExpected = 0;
      publishOta("idle");
    } else if (op == 0x01) {
      if (v.length() < 5) { publishOta("failed", 0, 0, "bad begin"); return; }
      otaExpected = ((uint32_t)(uint8_t)v[1] << 24)
                  | ((uint32_t)(uint8_t)v[2] << 16)
                  | ((uint32_t)(uint8_t)v[3] << 8)
                  |  (uint32_t)(uint8_t)v[4];
      otaReceived = 0;
      if (!Update.begin(otaExpected)) {
        publishOta("failed", 0, otaExpected, "Update.begin failed");
        return;
      }
      otaInProgress = true;
      // Reset rate-limit window so a fresh OTA starts clean.
      chunkLastReported = 0;
      chunkLastProgress = 0;
      publishOta("receiving", 0, otaExpected);
    } else if (op == 0x02) {
      if (!otaInProgress) { publishOta("failed", 0, 0, "no active session"); return; }
      size_t len = v.length() - 1;
      size_t w = Update.write((uint8_t*)(v.c_str() + 1), len);
      if (w != len) {
        Update.abort();
        otaInProgress = false;
        publishOta("failed", otaReceived, otaExpected, "write short");
        return;
      }
      otaReceived += len;
      // 1.6 MB / 180 B/chunk ≈ 9000 notifies — throttle to avoid saturating
      // the BLE stack once the dashboard switches to writeWithoutResponse.
      unsigned long now = millis();
      if (otaReceived - chunkLastReported > 32768 || now - chunkLastProgress > 250) {
        chunkLastReported = otaReceived;
        chunkLastProgress = now;
        publishOta("receiving", otaReceived, otaExpected);
      }
    } else if (op == 0x03) {
      if (!otaInProgress) { publishOta("failed", 0, 0, "no active session"); return; }
      publishOta("committing", otaReceived, otaExpected);
      if (!Update.end(true)) {
        otaInProgress = false;
        publishOta("failed", otaReceived, otaExpected, "Update.end failed");
        return;
      }
      publishOta("done", otaReceived, otaExpected);
      otaRestartPending = true;  // loop() restarts after onWrite returns
    } else if (op == 0x04) {
      // URL-trigger isn't in this build — HTTPClient + NetworkClientSecure +
      // mbedTLS were the cheapest IRAM cuts once camera libs joined, and BLE-
      // stream is the correct fallback. Replying "failed" tells the dashboard
      // to fall back automatically (see ota.js grace-window logic).
      publishOta("failed", 0, 0, "url-trigger unavailable in camera build");
    }
  }
};

// Arduino BLE stops advertising when a central connects and doesn't
// auto-resume on disconnect — restart it here so behavior matches the Pi
// (BlueZ keeps advertising by default) and the operator can reconnect
// without power-cycling the device.
//
// onConnect requests a tighter connection interval (15-30 ms range).
// macOS / Chrome default to 30 ms which limits notify rate to ~33/s —
// snapshot transfer at 9 KB / 50 chunks ≈ 1.5-2 s. With 15 ms accepted,
// throughput nearly doubles. Central can refuse; the request is a hint.
class ServerCallbacks : public BLEServerCallbacks {
  void onConnect(BLEServer* srv, NimBLEConnInfo& info) override {
    // Args: handle, min/max interval (×1.25 ms), latency, supervision (×10 ms)
    srv->updateConnParams(info.getConnHandle(), 12, 24, 0, 400);
  }
  void onDisconnect(BLEServer* /*srv*/, NimBLEConnInfo& /*info*/, int /*reason*/) override {
    BLEDevice::startAdvertising();
    Serial.println("client disconnected; advertising resumed");
  }
};

class LedCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch, NimBLEConnInfo& /*info*/) override {
    std::string value = ch->getValue();
    if (value.length() > 0) applyLed(value[0] != 0);
  }
};

// Single-byte 0..100 brightness write. Anything outside the range is
// clamped — Pip and the dashboard slider should both stay in [0, 100],
// but a hand-crafted BLE write shouldn't be able to overdrive the LED.
class FlashCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch, NimBLEConnInfo& /*info*/) override {
    std::string value = ch->getValue();
    if (value.length() > 0) applyFlash((uint8_t)value[0]);
  }
};

// Tiny JSON int extractor — same pattern wifi-join uses. Returns -1 when
// the key is missing OR the value isn't a parseable integer in [0, 99].
// We don't pull a JSON library; the schema is fixed and small.
static int extractIntKey(const std::string& json, const char* key) {
  std::string needle = "\""; needle += key; needle += "\"";
  size_t k = json.find(needle);
  if (k == std::string::npos) return -1;
  size_t c = json.find(':', k);
  if (c == std::string::npos) return -1;
  size_t i = c + 1;
  while (i < json.size() && (json[i] == ' ' || json[i] == '\t')) i++;
  int v = 0;
  bool any = false;
  while (i < json.size() && json[i] >= '0' && json[i] <= '9') {
    v = v * 10 + (json[i] - '0');
    i++; any = true;
  }
  return any ? v : -1;
}

// Pin-config write — JSON with the same keys loadPinConfig() reads. Validates
// each pin is in [0, 39] and not in the camera-reserved set; on success,
// writes NVS and schedules a restart.
class PinConfigCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch, NimBLEConnInfo& /*info*/) override {
    std::string json = ch->getValue();
    Serial.printf("pin-config: write len=%u\n", (unsigned)json.length());
    int led    = extractIntKey(json, "led");
    int flash  = extractIntKey(json, "flash");
    int l_in1  = extractIntKey(json, "m_l_in1");
    int l_in2  = extractIntKey(json, "m_l_in2");
    int r_in1  = extractIntKey(json, "m_r_in1");
    int r_in2  = extractIntKey(json, "m_r_in2");
    if (led < 0 || flash < 0 || l_in1 < 0 || l_in2 < 0 || r_in1 < 0 || r_in2 < 0) {
      Serial.printf("pin-config: missing keys, ignored\n");
      return;
    }
    // Camera pins — must not collide. Bake the reserved set in (it's the
    // AI-Thinker fixed pin map; changing the camera pins requires a code
    // change, not a config change).
    static const int RESERVED[] = { 0, 5, 18, 19, 21, 22, 23, 25, 26, 27, 32, 34, 35, 36, 39 };
    int candidates[6] = { led, flash, l_in1, l_in2, r_in1, r_in2 };
    for (int i = 0; i < 6; i++) {
      int p = candidates[i];
      if (p < 0 || p > 39) {
        Serial.printf("pin-config: pin %d out of range, ignored\n", p);
        return;
      }
      for (int r : RESERVED) {
        if (p == r) { Serial.printf("pin-config: GPIO %d is camera-reserved, ignored\n", p); return; }
      }
      // No-duplicate check among the editable pins themselves.
      for (int j = i + 1; j < 6; j++) {
        if (candidates[j] == p) {
          Serial.printf("pin-config: GPIO %d assigned twice, ignored\n", p);
          return;
        }
      }
    }
    Preferences pins;
    pins.begin("pins", false);  // read/write
    pins.putInt("led",     led);
    pins.putInt("flash",   flash);
    pins.putInt("m_l_in1", l_in1);
    pins.putInt("m_l_in2", l_in2);
    pins.putInt("m_r_in1", r_in1);
    pins.putInt("m_r_in2", r_in2);
    pins.end();
    Serial.printf("pin-config: saved (led=%d flash=%d L=%d/%d R=%d/%d) — restarting\n",
                  led, flash, l_in1, l_in2, r_in1, r_in2);
    pinConfigRestartPending = true;
  }
};

static void driveHalfBridge(int in1Pin, int in2Pin, int8_t signedSpeed) {
  if (!_motors_attached) return;
  int magnitude = signedSpeed < 0 ? -signedSpeed : signedSpeed;
  if (magnitude > 100) magnitude = 100;
  uint32_t duty = (magnitude * 255) / 100;
  if (signedSpeed >= 0) {
    ledcWrite(in1Pin, duty);
    ledcWrite(in2Pin, 0);
  } else {
    ledcWrite(in1Pin, 0);
    ledcWrite(in2Pin, duty);
  }
}

static void applyMotors(int8_t left, int8_t right) {
  motorLeft = left;
  motorRight = right;
  driveHalfBridge(MOTOR_L_IN1, MOTOR_L_IN2, left);
  driveHalfBridge(MOTOR_R_IN1, MOTOR_R_IN2, right);
  uint8_t buf[2] = { (uint8_t)left, (uint8_t)right };
  if (motorChar) {
    motorChar->setValue(buf, 2);
    motorChar->notify();
  }
  Serial.printf("motors → (%+d, %+d)\n", left, right);
}

class MotorCallbacks : public BLECharacteristicCallbacks {
  // Two payload shapes, parity with pi_robot.py:
  //   2 bytes [l, r]                 — persistent (user joystick). Watchdog
  //                                    handles auto-stop on silence.
  //   4 bytes [l, r, dur_hi, dur_lo] — time-bounded pulse (LLM). Clamped
  //                                    to LLM_MAX_SPEED / LLM_MAX_DURATION_MS.
  //                                    loop() auto-stops at motorPulseEndAt.
  // Every write bumps motorPulseId so a newer write invalidates an earlier
  // pulse's pending stop.
  void onWrite(BLECharacteristic* ch, NimBLEConnInfo& /*info*/) override {
    // std::string — motor payload is 2 or 4 raw bytes; a stop command is
    // {0, 0} and Arduino String(const char*) would read that as empty.
    std::string v = ch->getValue();
    motorLastWriteAt = millis();
    motorPulseId++;
    if (v.length() == 2) {
      applyMotors((int8_t)v[0], (int8_t)v[1]);
    } else if (v.length() == 4) {
      int8_t l = (int8_t)v[0];
      int8_t r = (int8_t)v[1];
      if (l < -LLM_MAX_SPEED) l = -LLM_MAX_SPEED;
      if (l >  LLM_MAX_SPEED) l =  LLM_MAX_SPEED;
      if (r < -LLM_MAX_SPEED) r = -LLM_MAX_SPEED;
      if (r >  LLM_MAX_SPEED) r =  LLM_MAX_SPEED;
      uint16_t dur = ((uint8_t)v[2] << 8) | (uint8_t)v[3];
      if (dur < 50)                     dur = 50;
      if (dur > LLM_MAX_DURATION_MS)    dur = LLM_MAX_DURATION_MS;
      applyMotors(l, r);
      motorActivePulseId = motorPulseId;
      motorPulseEndAt = millis() + dur;
    }
  }
};

class WifiScanCallbacks : public BLECharacteristicCallbacks {
  void onRead(BLECharacteristic* /*ch*/, NimBLEConnInfo& /*info*/) override { startScan(); }
};

class WifiJoinCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch, NimBLEConnInfo& /*info*/) override {
    std::string value = ch->getValue();
    // Payload spec: {"s":"...","p":"..."}.
    const size_t npos = std::string::npos;
    size_t sIdx = value.find("\"s\"");
    size_t pIdx = value.find("\"p\"");
    if (sIdx == npos) { publishStatus("failed", "", "missing ssid"); return; }
    auto extract = [&](size_t keyIdx) -> String {
      size_t colon = value.find(':', keyIdx);
      if (colon == npos) return "";
      size_t q1 = value.find('"', colon);
      if (q1 == npos) return "";
      size_t q2 = value.find('"', q1 + 1);
      while (q2 != npos && q2 > 0 && value[q2 - 1] == '\\') q2 = value.find('"', q2 + 1);
      if (q2 == npos) return "";
      return String(value.substr(q1 + 1, q2 - q1 - 1).c_str());
    };
    String ssid = extract(sIdx);
    String pass = (pIdx != npos) ? extract(pIdx) : "";
    if (ssid.length() == 0) { publishStatus("failed", "", "missing ssid"); return; }
    startJoin(ssid, pass);
  }
};

// Snapshot pipeline — runs in its own FreeRTOS task so the BLE write
// callback returns immediately. Captures a frame, sends as a chunked stream
// (begin/chunk/commit; same envelope OTA uses, just outbound). One snapshot
// at a time — overlapping requests during a transfer drop the new one.
static void snapshotTask(void* param) {
  Serial.printf("snapshot: task entered, heap=%u\n", ESP.getFreeHeap());
  if (!cameraReady) {
    Serial.printf("snapshot: no-camera\n");
    if (snapshotDataChar) {
      uint8_t err[1 + 16];
      err[0] = 0xff;
      const char* msg = "no-camera";
      size_t n = strlen(msg);
      memcpy(err + 1, msg, n);
      snapshotDataChar->setValue(err, 1 + n);
      snapshotDataChar->notify();
    }
    snapshotTaskHandle = nullptr;
    vTaskDelete(nullptr);
    return;
  }
  // Discard the head buffer first. With grab_mode=CAMERA_GRAB_LATEST + the
  // streamTask not actively pulling frames, the driver can hold a frame
  // captured minutes ago (last time the stream ran). Returning it forces
  // the driver to release the slot; the next fb_get blocks for the next
  // DMA-completed frame, which is fresh. Adds ~33 ms (one capture period
  // at OV2640's ~30 fps) — imperceptible to the operator.
  camera_fb_t* stale = esp_camera_fb_get();
  if (stale) esp_camera_fb_return(stale);
  camera_fb_t* fb = esp_camera_fb_get();
  if (!fb) {
    Serial.printf("snapshot: fb-get-failed\n");
    if (snapshotDataChar) {
      uint8_t err[1 + 16];
      err[0] = 0xff;
      const char* msg = "fb-get-failed";
      size_t n = strlen(msg);
      memcpy(err + 1, msg, n);
      snapshotDataChar->setValue(err, 1 + n);
      snapshotDataChar->notify();
    }
    snapshotTaskHandle = nullptr;
    vTaskDelete(nullptr);
    return;
  }
  Serial.printf("snapshot: fb captured, %u bytes\n", (unsigned)fb->len);

  // Begin: opcode 0x01 + total size (u32 BE). Dashboard pre-allocates a
  // buffer so it can show progress (n received / total) instead of a spinner.
  uint8_t begin[5];
  begin[0] = 0x01;
  begin[1] = (fb->len >> 24) & 0xff;
  begin[2] = (fb->len >> 16) & 0xff;
  begin[3] = (fb->len >>  8) & 0xff;
  begin[4] = (fb->len      ) & 0xff;
  snapshotDataChar->setValue(begin, 5);
  snapshotDataChar->notify();
  // Pace begin → chunk 0 the same way every chunk → next-chunk pair is
  // paced. Without this the begin notify and chunk 0's notify queue
  // back-to-back; NimBLE's shallow tx queue drops one of the pair, and
  // observed behavior is begin being the casualty — every subsequent
  // chunk then arrives at the dashboard without a buffer to land in
  // and is silently ignored. Symptom: dashboard log shows op=0x02
  // notifies arriving but no image ever rendering.
  vTaskDelay(pdMS_TO_TICKS(40));

  // Chunks: opcode 0x02 + payload. Loop with small yields between to let the
  // BLE stack drain its tx queue — sending too fast on classic ESP32 BLE
  // overflows the controller and notifies silently drop.
  size_t sent = 0;
  uint8_t chunk[1 + SNAPSHOT_CHUNK_BYTES];
  chunk[0] = 0x02;
  while (sent < fb->len) {
    size_t take = fb->len - sent;
    if (take > SNAPSHOT_CHUNK_BYTES) take = SNAPSHOT_CHUNK_BYTES;
    memcpy(chunk + 1, fb->buf + sent, take);
    snapshotDataChar->setValue(chunk, 1 + take);
    snapshotDataChar->notify();
    sent += take;
    // Sender rate must stay ≤ the central's notify-delivery rate (one notify
    // per connection event). Mac/Chrome negotiates ~30 ms, so a 25 ms delay
    // is FASTER than delivery — Bluedroid's ~7-entry tx queue drifts full
    // over ~1 s of transfer and silently drops the tail (saw stalls at
    // ~6.5 KB / 9 KB JPEGs). 40 ms keeps a safe margin above the interval;
    // ~9 KB JPEG ≈ 50 chunks ≈ 2 s, which is fine for a single snapshot.
    vTaskDelay(pdMS_TO_TICKS(40));
  }

  // Commit: opcode 0x03, no payload. Dashboard validates received == total.
  uint8_t commit[1] = { 0x03 };
  snapshotDataChar->setValue(commit, 1);
  snapshotDataChar->notify();

  esp_camera_fb_return(fb);
  Serial.printf("snapshot: sent %u bytes\n", (unsigned)sent);
  snapshotTaskHandle = nullptr;
  vTaskDelete(nullptr);
}

class SnapshotRequestCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* c, NimBLEConnInfo& /*info*/) override {
    // Diagnostic instrumentation — without these logs there's no way to
    // tell whether the write reached us, was rejected on opcode, was
    // refused as a duplicate, or silently failed at task creation.
    std::string v = c->getValue();
    Serial.printf("snapshot: onWrite, len=%u, op=%02x\n",
                  (unsigned)v.length(), v.length() ? (uint8_t)v[0] : 0xff);
    if (v.length() < 1 || (uint8_t)v[0] != 0x01) {
      Serial.printf("snapshot: rejected — bad opcode\n");
      return;
    }
    if (snapshotTaskHandle != nullptr) {
      Serial.printf("snapshot: ignored — transfer in progress\n");
      return;
    }
    Serial.printf("snapshot: heap free=%u, largest=%u\n",
                  ESP.getFreeHeap(),
                  heap_caps_get_largest_free_block(MALLOC_CAP_8BIT));
    // 4 KB stack — chunk loop is shallow (was 8 KB out of paranoia, but
    // we've been bumping into "no contiguous heap" with 18 KB total free
    // post-camera-init, and 8 KB doesn't fit in a fragmented heap).
    BaseType_t rc = xTaskCreatePinnedToCore(
      snapshotTask, "snapshot", 4096, nullptr, 1, &snapshotTaskHandle, 1);
    Serial.printf("snapshot: xTaskCreate rc=%d, handle=%p\n",
                  (int)rc, (void*)snapshotTaskHandle);
    if (rc != pdPASS && snapshotDataChar) {
      // If the task didn't start, the dashboard would otherwise wait on
      // its watchdog (4 s of silence). Push an explicit error notify so
      // the user sees "snapshot: task-create-failed" instead of "stalled".
      uint8_t err[1 + 24];
      err[0] = 0xff;
      const char* msg = "task-create-failed";
      size_t n = strlen(msg);
      memcpy(err + 1, msg, n);
      snapshotDataChar->setValue(err, 1 + n);
      snapshotDataChar->notify();
    }
  }
};

// Camera profile picker. Write {"profile":"compact|standard|full"}; the
// firmware persists to Preferences and restarts so a fresh setup() applies
// the new profile (initCamera reads cameraProfile at boot, no hot-swap).
class CameraProfileCallbacks : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* c, NimBLEConnInfo& /*info*/) override {
    std::string v = c->getValue();
    const size_t npos = std::string::npos;
    size_t q = v.find("\"profile\"");
    if (q == npos) { Serial.println("camera-profile: bad payload"); return; }
    size_t colon = v.find(':', q);
    size_t firstQ = (colon == npos) ? npos : v.find('"', colon);
    size_t lastQ  = (firstQ == npos) ? npos : v.find('"', firstQ + 1);
    if (firstQ == npos || lastQ == npos) { Serial.println("camera-profile: bad payload"); return; }
    String name(v.substr(firstQ + 1, lastQ - firstQ - 1).c_str());
    CamProfile next = cameraProfileFromName(name);
    if (next == cameraProfile) {
      Serial.printf("camera-profile: already %s, no-op\n", cameraProfileName(next));
      return;
    }
    prefs.begin("cam", false);
    prefs.putInt("profile", (int)next);
    prefs.end();
    Serial.printf("camera-profile: %s → %s, restarting\n",
                  cameraProfileName(cameraProfile), cameraProfileName(next));
    otaRestartPending = true;  // loop() handles the restart with a 500ms drain
  }
};

// Load pin overrides from NVS. Each key is optional; missing keys keep
// the compile-time safe default. Mirrors the Pi's pi-robot.conf reader,
// but key/value (NVS) instead of JSON. Dashboard pinout editor (item D
// in working.md) will write into this same namespace.
static void loadPinConfig() {
  Preferences pins;
  pins.begin("pins", true);  // read-only
  LED_PIN     = pins.getInt("led",        LED_PIN);
  FLASH_PIN   = pins.getInt("flash",      FLASH_PIN);
  MOTOR_L_IN1 = pins.getInt("m_l_in1",    MOTOR_L_IN1);
  MOTOR_L_IN2 = pins.getInt("m_l_in2",    MOTOR_L_IN2);
  MOTOR_R_IN1 = pins.getInt("m_r_in1",    MOTOR_R_IN1);
  MOTOR_R_IN2 = pins.getInt("m_r_in2",    MOTOR_R_IN2);
  pins.end();
}

// Flash LED PWM. Same ledc API as motors; separate channel so motor PWM
// duty doesn't bleed into the flash output. 1 kHz / 8-bit duty matches
// motors — keeps LEDC config uniform.
static void initFlashPwm() {
  _flash_attached = ledcAttach(FLASH_PIN, MOTOR_PWM_FREQ, MOTOR_PWM_RES);
  if (!_flash_attached) {
    Serial.printf("flash: ledcAttach(%d) failed\n", FLASH_PIN);
    return;
  }
  ledcWrite(FLASH_PIN, 0);
  Serial.printf("flash: PWM ready on GPIO %d\n", FLASH_PIN);
}

static void applyFlash(uint8_t level) {
  if (level > 100) level = 100;
  flashLevel = level;
  if (_flash_attached) {
    uint32_t duty = ((uint32_t)level * 255) / 100;
    ledcWrite(FLASH_PIN, duty);
  }
  if (flashChar) {
    flashChar->setValue(&flashLevel, 1);
    if (bleServiceStarted) flashChar->notify();
  }
}

// Attach LEDC PWM to the four motor input pins. Failure on any single
// pin disables the whole motor subsystem so we don't drive half a motor;
// applyMotors short-circuits when _motors_attached is false.
static void initMotorPwm() {
  bool ok = true;
  ok &= ledcAttach(MOTOR_L_IN1, MOTOR_PWM_FREQ, MOTOR_PWM_RES);
  ok &= ledcAttach(MOTOR_L_IN2, MOTOR_PWM_FREQ, MOTOR_PWM_RES);
  ok &= ledcAttach(MOTOR_R_IN1, MOTOR_PWM_FREQ, MOTOR_PWM_RES);
  ok &= ledcAttach(MOTOR_R_IN2, MOTOR_PWM_FREQ, MOTOR_PWM_RES);
  _motors_attached = ok;
  if (!ok) {
    Serial.printf("motors: ledcAttach failed (pins %d/%d/%d/%d) — motors disabled\n",
                  MOTOR_L_IN1, MOTOR_L_IN2, MOTOR_R_IN1, MOTOR_R_IN2);
    return;
  }
  ledcWrite(MOTOR_L_IN1, 0); ledcWrite(MOTOR_L_IN2, 0);
  ledcWrite(MOTOR_R_IN1, 0); ledcWrite(MOTOR_R_IN2, 0);
  Serial.printf("motors: PWM ready, L=%d/%d R=%d/%d\n",
                MOTOR_L_IN1, MOTOR_L_IN2, MOTOR_R_IN1, MOTOR_R_IN2);
}

void setup() {
  // AI-Thinker's AMS1117 LDO sags hard when WiFi TX bursts coincide with
  // camera DMA + BLE radio activity. Default brownout trips at ~2.43 V
  // and resets the chip mid-stream — the most common ESP32-CAM stability
  // complaint. Disabling means a real undervoltage event won't auto-
  // protect (chip behaves oddly instead of resetting cleanly), but the
  // alternative is constant reboots under normal load. The 470 µF + 0.1 µF
  // hardware mod across the AMS1117 output (see HARDWARE.md) is the
  // belt-and-braces complement to this firmware-side disable.
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);

  Serial.begin(115200);
  loadPinConfig();
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, HIGH);  // off
  initMotorPwm();
  initFlashPwm();
  // Stop the wheels on any clean restart (OTA reboot, ESP.restart, etc.)
  // so the L298N doesn't hold the last duty for the ~500 ms it takes to
  // reset the firmware. Brownout / panic don't fire this — same as the Pi.
  esp_register_shutdown_handler([](){
    if (_motors_attached) {
      ledcWrite(MOTOR_L_IN1, 0); ledcWrite(MOTOR_L_IN2, 0);
      ledcWrite(MOTOR_R_IN1, 0); ledcWrite(MOTOR_R_IN2, 0);
    }
    if (_flash_attached) ledcWrite(FLASH_PIN, 0);
  });

  // Tried `esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT)` here to
  // reclaim the Classic BT DRAM pool for WiFi — pair succeeded but the
  // GATT server dropped the connection immediately after ("GATT Server is
  // disconnected"). Arduino-esp32 3.3.8's built-in BT controller appears
  // to need the Classic BT memory during init even when only BLE is used.
  // Do not re-add without also switching the controller mode explicitly.

  // Stable per-chip suffix — low 16 bits of the WiFi MAC. "BR-" prefix
  // (was "BetterRobot-") shortens the BLE-advertised name + the mDNS
  // hostname (br-e9d4.local vs betterrobot-e9d4.local) so it fits cleanly
  // in narrow card widths and on the Web Bluetooth chooser. The dashboard's
  // split-on-last-hyphen prefix-dimming logic is prefix-agnostic.
  uint64_t chipid = ESP.getEfuseMac();
  snprintf(robotName, sizeof(robotName), "BR-%04X", (uint16_t)(chipid & 0xFFFF));
  const char* name = robotName;  // local alias keeps the rest of setup unchanged

  // Allocation order on classic ESP32-CAM where BLE + WiFi + esp32-camera
  // compete for ~250 KB of DRAM. BLE before WiFi — Bluedroid AND NimBLE
  // both need their kernel-object pool to fit while heap is mostly fresh,
  // and WiFi.init is forgiving about being last (it just comes up with
  // fewer RX buffers). The reverse order panics BLE (FreeRTOS NULL pxQueue
  // crash on Bluedroid; silent advertising failure on NimBLE).
  //   1) Camera — 32 KB DMA buffer in internal DRAM (PSRAM isn't DMA-
  //      coherent on classic ESP32); framebuffers live in PSRAM.
  //   2) BLE (NimBLE) — host stack + per-char semaphores.
  //   3) WiFi — whatever's left. Marginal on this board; WiFi may come
  //      up with only 1 of 4 RX buffers or fail to init entirely
  //      (ESP_ERR_WIFI_NOT_INIT / 0x3001). Use the "compact" camera
  //      profile to free DRAM if WiFi needs breathing room.

  // Camera profile is read once at boot — changing it via the BLE write
  // char persists to Preferences and restarts the device so a fresh setup()
  // re-runs initCamera with the new profile.
  prefs.begin("cam", true);   // read-only
  // Compact (QVGA) is the daily-use default — on classic ESP32-CAM with
  // 1-of-4 WiFi RX buffers, standard (VGA) sustains ~15 fps and full
  // (SVGA) ~10 fps, both of which feel laggy. Compact sustains 30+ fps
  // and the resolution loss is acceptable for stream + VLM/detector
  // input. Operators who want higher-res snapshots flip via the profile
  // picker on the camera card; that choice persists in NVS and overrides
  // this default on subsequent boots.
  cameraProfile = (CamProfile)prefs.getInt("profile", (int)CAM_COMPACT);
  prefs.end();

  cameraReady = initCamera();

  BLEDevice::init(name);
  // Lock our preferred MTU at the host max (247) so a central that
  // negotiates anything below 184 doesn't silently break snapshots
  // (chunks are 180 B + opcode + 3 ATT header = 184 minimum). Chrome on
  // macOS picks ~185 today; the explicit setMTU is insurance.
  BLEDevice::setMTU(247);
  // +9 dBm — match the WiFi tx power (which is +19.5 dBm) so BLE doesn't
  // get drowned out by the camera-module antenna shadow. Default is 0 dBm,
  // which is asymmetrically weak in a robotics deployment.
  BLEDevice::setPower(9);
  BLEServer* server = BLEDevice::createServer();
  server->setCallbacks(new ServerCallbacks());
  BLEService* service = server->createService(SERVICE_UUID);

  ledChar = service->createCharacteristic(
    LED_CHAR_UUID,
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::NOTIFY
  );
  ledChar->setCallbacks(new LedCallbacks());
  uint8_t initial = 0;
  ledChar->setValue(&initial, 1);

  // Flash LED — only when ledcAttach succeeded; otherwise the cap is hidden
  // from fw-info too. No half-broken state where the dashboard offers a
  // slider and writes silently get dropped.
  if (_flash_attached) {
    flashChar = service->createCharacteristic(
      FLASH_CHAR_UUID,
      NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::NOTIFY
    );
    flashChar->setCallbacks(new FlashCallbacks());
    flashChar->setValue(&flashLevel, 1);
  }

  // Pin-config write surface — fed by the dashboard's Pinout editor. JSON
  // schema parsed in PinConfigCallbacks; validates against the camera-
  // reserved pin set before writing NVS and rebooting.
  pinConfigChar = service->createCharacteristic(
    PIN_CONFIG_CHAR_UUID,
    NIMBLE_PROPERTY::WRITE
  );
  pinConfigChar->setCallbacks(new PinConfigCallbacks());

  wifiScanChar = service->createCharacteristic(
    WIFI_SCAN_CHAR_UUID,
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY
  );
  wifiScanChar->setCallbacks(new WifiScanCallbacks());
  wifiScanChar->setValue("[]");

  wifiJoinChar = service->createCharacteristic(
    WIFI_JOIN_CHAR_UUID,
    NIMBLE_PROPERTY::WRITE
  );
  wifiJoinChar->setCallbacks(new WifiJoinCallbacks());

  wifiStatusChar = service->createCharacteristic(
    WIFI_STATUS_CHAR_UUID,
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY
  );
  wifiStatusChar->setValue("{\"st\":\"idle\"}");

  otaDataChar = service->createCharacteristic(
    OTA_DATA_CHAR_UUID,
    // WRITE | WRITE_NR — without-response lets the dashboard stream chunks
    // without per-frame ATT acks once we reintroduce the WithoutResponse
    // client-side. Advertising both keeps WithResponse as a fallback.
    NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::WRITE_NR
  );
  otaDataChar->setCallbacks(new OtaDataCallbacks());

  otaStatusChar = service->createCharacteristic(
    OTA_STATUS_CHAR_UUID,
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY
  );
  otaStatusChar->setValue("{\"st\":\"idle\"}");

  fwInfoChar = service->createCharacteristic(
    FW_INFO_CHAR_UUID,
    // NOTIFY is retained for future schema changes (e.g. cap added at
    // runtime). Today camera is init'd in setup() so the initial read already
    // has everything; dashboard subscribes defensively but won't see updates
    // in normal operation.
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY
  );
  publishFwInfo();

  motorChar = service->createCharacteristic(
    MOTOR_CHAR_UUID,
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::NOTIFY
  );
  motorChar->setCallbacks(new MotorCallbacks());
  uint8_t motorInit[2] = { 0, 0 };
  motorChar->setValue(motorInit, 2);

  // Telemetry: system-health observability matched to Pi's TELEMETRY_CHAR_UUID
  // shape. ESP32 has one binary so there's no "main service down, device fine"
  // state to recover from — the value here is *diagnostic*, not a separate
  // recovery plane. JSON: {uptime_ms, free_heap, free_psram, reset_reason, sha}.
  telemetryChar = service->createCharacteristic(
    TELEMETRY_CHAR_UUID,
    NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY
  );
  telemetryChar->setValue("{}");

  // BLE snapshot — see snapshotTask() for the wire format. Two chars: a
  // single-byte write trigger and a notify-only outbound stream. Only
  // registered if the camera came up.
  if (cameraReady) {
    snapshotRequestChar = service->createCharacteristic(
      SNAPSHOT_REQUEST_CHAR_UUID,
      NIMBLE_PROPERTY::WRITE
    );
    snapshotRequestChar->setCallbacks(new SnapshotRequestCallbacks());

    snapshotDataChar = service->createCharacteristic(
      SNAPSHOT_DATA_CHAR_UUID,
      NIMBLE_PROPERTY::NOTIFY
    );

    // Camera profile picker — write JSON to change. Firmware restarts on
    // change so the new profile takes effect via a fresh initCamera.
    cameraProfileChar = service->createCharacteristic(
      CAMERA_PROFILE_CHAR_UUID,
      NIMBLE_PROPERTY::WRITE
    );
    cameraProfileChar->setCallbacks(new CameraProfileCallbacks());
  }

  service->start();
  bleServiceStarted = true;

  BLEAdvertising* adv = BLEDevice::getAdvertising();
  adv->setName(name);
  adv->addServiceUUID(SERVICE_UUID);
  adv->enableScanResponse(true);
  adv->start();

  Serial.printf("\nAdvertising as %s\n", name);

  // WiFi last. `WiFi.mode(WIFI_STA)` runs esp_wifi_init + esp_wifi_start.
  // setSleep(false) keeps the radio awake during BLE windows (default DTIM
  // sleep drops beacons and makes scans come back empty). Max TX power
  // helps cut through the antenna shadow from an attached camera module.
  // Hostname makes the device identifiable on a router admin page when
  // discover.js isn't available (operator-side debug). Auto-reconnect
  // closes the silent-dead-link hole — without it, a post-join drop
  // (AP power-cycle, channel hop) leaves the firmware permanently stuck
  // and the dashboard sees stale state. persistent(false) skips two NVS
  // writes per WiFi.begin() — meaningful on a heap-tight boot.
  char hn[32];
  snprintf(hn, sizeof(hn), "esp32-robot-%04X", (uint16_t)(chipid & 0xFFFF));
  WiFi.setHostname(hn);
  WiFi.persistent(false);
  WiFi.setAutoReconnect(true);
  WiFi.mode(WIFI_STA);
  WiFi.setSleep(false);
  // Pin power-save off past coex re-assertion. setSleep(false) should imply
  // PS_NONE, but on arduino-esp32 3.x with BLE coex the state can be
  // re-asserted by the coex logic. Belt-and-suspenders.
  esp_wifi_set_ps(WIFI_PS_NONE);
  // Drop legacy 802.11b. b-rates (1/2/5.5/11 Mbps) burn far more airtime
  // per byte than g/n; on a saturated AP, dropping b reduces retransmits
  // ~10-20% for OTA and smooths MJPEG streams. Modern APs are g/n; pre-2010
  // b-only APs would refuse — accept that trade.
  esp_wifi_set_protocol(WIFI_IF_STA, WIFI_PROTOCOL_11G | WIFI_PROTOCOL_11N);
  WiFi.setTxPower(WIFI_POWER_19_5dBm);
  WiFi.onEvent([](WiFiEvent_t e, WiFiEventInfo_t info){
    if (e == ARDUINO_EVENT_WIFI_STA_GOT_IP) {
      publishStatus("joined", WiFi.SSID(), "", WiFi.localIP().toString());
      publishFwInfo();
    } else if (e == ARDUINO_EVENT_WIFI_STA_DISCONNECTED) {
      publishStatus("reconnecting", WiFi.SSID(), "");
    }
  });
  Serial.printf("wifi up, free heap=%u, largest dma block=%u\n",
                ESP.getFreeHeap(), heap_caps_get_largest_free_block(MALLOC_CAP_DMA));

  prefs.begin("wifi", true);
  String savedSsid = prefs.getString("ssid", "");
  String savedPass = prefs.getString("pass", "");
  prefs.end();
  if (savedSsid.length()) {
    startJoin(savedSsid, savedPass);
  }

  // mDNS service advertisement so the dashboard can resolve
  // <robotName>.local without a server-side rendezvous. Idempotent;
  // begin() is safe to call before STA fully joins (the netif catches up).
  startMdnsPresence();
}

// === Presence plane: mDNS + /health =========================================
// Each robot publishes itself as `<robotName>._http._tcp.local` once WiFi
// joins. The dashboard probes `http://<robotName>.local:81/health` for
// every paired robot in localStorage — first OK wins, no internet
// rendezvous, no TLS, no third-party server.
//
// We had a signal.neevs.io PUT publisher here briefly. On classic ESP32-CAM
// the mbedTLS handshake fails reliably under the camera+BLE+WiFi DRAM
// budget, and the cross-network presence the rendezvous bought us isn't
// part of this project's toy-scale scope (CLAUDE.md). Dropped — saves
// ~90 KB flash + ~30 KB heap for the handshake.
static void startMdnsPresence() {
  // MDNS.begin lowercases the hostname automatically. addService advertises
  // the HTTP server already running on port 81 (/stream, /ota, /health).
  if (!MDNS.begin(robotName)) {
    Serial.println("mDNS: begin failed");
    return;
  }
  MDNS.addService("http", "tcp", 81);
  Serial.printf("mDNS: %s.local advertised\n", robotName);
}

// Map esp_reset_reason() to a short human label. Useful when the dashboard
// surfaces a recent crash — "panic" / "watchdog" tells a different story than
// "power-on" or "deepsleep".
static const char* resetReasonLabel(esp_reset_reason_t r) {
  switch (r) {
    case ESP_RST_POWERON:  return "poweron";
    case ESP_RST_EXT:      return "ext";
    case ESP_RST_SW:       return "sw";
    case ESP_RST_PANIC:    return "panic";
    case ESP_RST_INT_WDT:  return "int-wdt";
    case ESP_RST_TASK_WDT: return "task-wdt";
    case ESP_RST_WDT:      return "wdt";
    case ESP_RST_DEEPSLEEP:return "deepsleep";
    case ESP_RST_BROWNOUT: return "brownout";
    case ESP_RST_SDIO:     return "sdio";
    default:               return "unknown";
  }
}

static void publishTelemetry() {
  if (!telemetryChar) return;
  String ip = (WiFi.status() == WL_CONNECTED) ? WiFi.localIP().toString() : "";
  // min_free_heap is the worst-case watermark across uptime — reveals slow
  // leaks before they crash a malloc, which instantaneous free_heap hides.
  String t = "{\"uptime_ms\":" + String((unsigned long)millis())
           + ",\"free_heap\":" + String((unsigned long)esp_get_free_heap_size())
           + ",\"min_free_heap\":" + String((unsigned long)esp_get_minimum_free_heap_size())
           + ",\"free_psram\":" + String((unsigned long)heap_caps_get_free_size(MALLOC_CAP_SPIRAM))
           + ",\"reset_reason\":\"" + String(resetReasonLabel(esp_reset_reason())) + "\""
           + ",\"sha\":\"" GIT_SHA "\"";
  if (ip.length()) t += ",\"ip\":\"" + ip + "\"";
  t += "}";
  telemetryChar->setValue(t.c_str());
  if (bleServiceStarted) telemetryChar->notify();
}

void loop() {
  if (otaRestartPending) {
    delay(500);  // let the last notify + ATT response land
    ESP.restart();
  }
  if (pinConfigRestartPending) {
    delay(500);  // let the last ATT response land before BLE drops
    ESP.restart();
  }

  if (millis() - lastTelemetryAt > TELEMETRY_INTERVAL_MS) {
    publishTelemetry();
    lastTelemetryAt = millis();
  }

  if ((motorLeft != 0 || motorRight != 0)
      && motorLastWriteAt > 0
      && millis() - motorLastWriteAt > MOTOR_WATCHDOG_MS) {
    applyMotors(0, 0);
    Serial.printf("motor watchdog: stopped\n");
  }

  // LLM pulse auto-stop. Only fires if we're still the active pulse; a
  // newer joystick write or pulse would have bumped motorPulseId and
  // invalidated this end-time.
  if (motorPulseEndAt > 0
      && motorActivePulseId == motorPulseId
      && millis() >= motorPulseEndAt) {
    applyMotors(0, 0);
    motorPulseEndAt = 0;
    Serial.printf("motor pulse ended\n");
  }

  if (wifiPhase == PHASE_SCANNING) {
    int n = WiFi.scanComplete();
    if (n >= 0 || n == WIFI_SCAN_FAILED) {
      Serial.printf("wifi scan complete: n=%d after %lu ms\n", n, millis() - scanStartedAt);
      if (n >= 0) {
        publishScan();
      } else if (wifiScanChar) {
        // WIFI_SCAN_FAILED — notify empty so the dashboard clears its
        // "scanning…" spinner promptly instead of waiting for its own
        // 20s failsafe.
        wifiScanChar->setValue((uint8_t*)"[]", 2);
        wifiScanChar->notify();
      }
      wifiPhase = PHASE_IDLE;
    } else if (millis() - scanStartedAt > 30000) {
      // Failsafe: classic ESP32 with BLE active occasionally never reports
      // scan-complete. Don't leave the state machine wedged forever.
      // 30s covers the slower passive-scan path.
      Serial.printf("wifi scan abandoned after 30s (n=%d) — releasing state\n", n);
      WiFi.scanDelete();
      wifiPhase = PHASE_IDLE;
      // Publish empty list so the dashboard's notify listener clears its
      // "scanning…" UI rather than waiting for its own 20s timeout.
      if (wifiScanChar) {
        wifiScanChar->setValue((uint8_t*)"[]", 2);
        wifiScanChar->notify();
      }
    }
  } else if (wifiPhase == PHASE_JOINING) {
    wl_status_t s = WiFi.status();
    if (s == WL_CONNECTED) {
      wifiPhase = PHASE_IDLE;
      prefs.begin("wifi", false);
      prefs.putString("ssid", pendingSsid);
      prefs.putString("pass", pendingPass);
      prefs.end();
      // IP is what the dashboard needs to open the MJPEG stream. Surface it
      // on wifi-status (notify) so a later-attached dashboard picks it up.
      publishStatus("joined", pendingSsid, "", WiFi.localIP().toString());
      if (cameraReady) startCameraServer();
    } else if (s == WL_NO_SSID_AVAIL || s == WL_CONNECT_FAILED ||
               millis() - joinStartedAt > JOIN_TIMEOUT_MS) {
      wifiPhase = PHASE_IDLE;
      const char* err = (s == WL_NO_SSID_AVAIL) ? "ssid not found"
                      : (s == WL_CONNECT_FAILED) ? "connect failed"
                      : "timeout";
      WiFi.disconnect(true, false);
      publishStatus("failed", pendingSsid, err);
    }
  }
  delay(100);
}
