#!/usr/bin/env python3
"""Generate UUID constant files for ESP32 firmware (C header), Pi firmware
(Python module), and dashboard (JS module) from a single source of truth.

Source: protocol/uuids.json
Outputs:
    firmware/esp32_robot_idf/main/uuids.h    — `#define X "uuid"`
    firmware/pi_robot/uuids.py      — `X = "uuid"`
    public/uuids.js                 — `export const X = "uuid";`

The generated files include a banner that says they're generated; editing
them by hand is wasted effort because the next build will overwrite. Run
manually with `python3 tools/gen-uuids.py` or via `make gen-uuids` (which
the firmware compile / publish targets depend on).
"""
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO_ROOT, "protocol", "uuids.json")

BANNER_C = (
    "// Generated by tools/gen-uuids.py from protocol/uuids.json — do not edit.\n"
    "// Run `make gen-uuids` (or `python3 tools/gen-uuids.py`) after editing the JSON.\n"
)
BANNER_PY = (
    "# Generated by tools/gen-uuids.py from protocol/uuids.json — do not edit.\n"
    "# Run `make gen-uuids` (or `python3 tools/gen-uuids.py`) after editing the JSON.\n"
)
BANNER_JS = (
    "// Generated by tools/gen-uuids.py from protocol/uuids.json — do not edit.\n"
    "// Run `make gen-uuids` (or `python3 tools/gen-uuids.py`) after editing the JSON.\n"
)


def flatten(spec):
    """Walk the {service: {NAME: uuid}} structure into [(service, NAME, uuid)]."""
    for service, kvs in spec.items():
        if service.startswith("_"):
            continue
        for name, uuid in kvs.items():
            yield service, name, uuid


def write_if_changed(path, content):
    """No-op write when the file already matches — keeps Make's mtime checks
    happy and avoids spurious commits when nothing actually changed."""
    if os.path.exists(path):
        with open(path) as f:
            if f.read() == content:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return True


def gen_c(spec, path):
    out = [BANNER_C, "#pragma once\n\n"]
    last_service = None
    for service, name, uuid in flatten(spec):
        if service != last_service:
            if last_service is not None:
                out.append("\n")
            out.append(f"// {service}\n")
            last_service = service
        out.append(f'#define {name:32} "{uuid}"\n')
    return write_if_changed(path, "".join(out))


def gen_py(spec, path):
    out = [BANNER_PY, "\n"]
    last_service = None
    for service, name, uuid in flatten(spec):
        if service != last_service:
            if last_service is not None:
                out.append("\n")
            out.append(f"# {service}\n")
            last_service = service
        out.append(f'{name} = "{uuid}"\n')
    return write_if_changed(path, "".join(out))


def gen_js(spec, path):
    out = [BANNER_JS, "\n"]
    last_service = None
    for service, name, uuid in flatten(spec):
        if service != last_service:
            if last_service is not None:
                out.append("\n")
            out.append(f"// {service}\n")
            last_service = service
        out.append(f'export const {name} = "{uuid}";\n')
    return write_if_changed(path, "".join(out))


def main():
    with open(SOURCE) as f:
        spec = json.load(f)
    targets = [
        ("firmware/esp32_robot_idf/main/uuids.h", gen_c),
        ("firmware/pi_robot/uuids.py",   gen_py),
        ("public/uuids.js",              gen_js),
    ]
    changed = []
    for rel, gen in targets:
        path = os.path.join(REPO_ROOT, rel)
        if gen(spec, path):
            changed.append(rel)
    if changed:
        for c in changed:
            print(f"updated {c}")
    else:
        print("uuids: up to date")


if __name__ == "__main__":
    sys.exit(main())
